### ISSUE TITLE
Server's certificate chain is incomplete

### ISSUE THREAD

**Issue by KurtTheBerner** [Yannik/qnap-letsencrypt#1]
First I would like to thank you for writing these exact instructions for installing a letsencrypt certificate. 
I did everything step by step and it worked, but unfortunately on some clients I still get a certificate Error. I then checked the site using the service on https://www.ssllabs.com/ssltest/ and I got the overall Rating B with the warning Message "This server's certificate chain is incomplete."
What does this mean?

My questions:
- Do I have to modify the file /etc/config/apache/extra/httpd-ssl-vhosts-user.conf and add Entries for SSLCertificateKeyFile and SSLCertificateChainFile?
- Do I have to generate /etc/ssl/certs as it's stated in your FAQ Section? What about a Reboot, all is lost in this folder.

Thanks for your help

**Comment by Yannik** [comment]
Hi,

please post the detailed output of the section "Certification Path" of the ssltest. (This is regarding the certificate chain)
>Do I have to modify the file /etc/config/apache/extra/httpd-ssl-vhosts-user.conf and add Entries for SSLCertificateKeyFile and SSLCertificateChainFile?

No, as apache just serves http and the SSL layer is done by stunnel. `/etc/stunnel/stunnel.conf` is the key configuration file. Post your `ciphers` line and we will see why you only get a B rating. 

> Do I have to generate /etc/ssl/certs as it's stated in your FAQ Section? What about a Reboot, all is lost in this folder.

No, you don't have to. As you noted, it is pretty useless as it's gone after a reboot. It is not needed at all but I just wrote it down because that's what I did first (when I didn't know it was gone after a reboot).

**Comment by KurtTheBerner** [comment]
Hi Yannik,
Here my SSLCipherSuite Entry:
`SSLCipherSuite ALL:!aNULL:!ADH:!eNULL:!SSLv2:!LOW:!EXP:!RC4:+HIGH:+MEDI$`
I have an additional Entry to disable SSLv2 and SSLv3 (without this Entry I got only a F Rating):
`SSLProtocol All -SSLv2 -SSLv3`

Certification Path Details:
![certificatepaths](https://cloud.githubusercontent.com/assets/16208159/13643382/c612eee0-e620-11e5-9b7b-b1bc65785527.jpg)

**Comment by Yannik** [comment]
Please
 * double check that /etc/stunnel/stunnel.pem contains both `letsencrypt/keys/domain.key` and `letsencrypt/chained.pem`
 * Post your whole `stunnel.conf` here
 * Post the output of `stunnel -version`

**Comment by KurtTheBerner** [comment]
Hi Yannik
Here is the Information:
/etc/stunnel/stunnel.pem contains domain.key and chained.pem

`/etc/stunnel/stunnel.conf`
```
cert = /etc/stunnel/stunnel.pem
;key = /usr/local/etc/stunnel/mail.pem
ciphers = ALL:!SSLv2:!LOW:!EXPORT40:@STRENGTH
;chroot = /usr/local/var/lib/stunnel/
setuid = admin
setgid = administrators
; PID is created inside chroot jail
pid = /var/run/stunnel.pid
; Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
;compression = rle
```
`stunnel -version:`
```
stunnel 4.32 on i686-pc-linux-gnu with OpenSSL 1.0.1p 9 Jul 2015
Threading:FORK SSL:ENGINE Sockets:POLL,IPv6

Global options
debug           = daemon.notice
pid             = /usr/local/var/run/stunnel/stunnel.pid
RNDbytes        = 64
RNDfile         = /dev/urandom
RNDoverwrite    = yes

Service-level options
cert            = /usr/local/etc/stunnel/stunnel.pem
ciphers         = ALL:!EXPORT:!aNULL:!eNULL:!SSLv2
session         = 300 seconds
sslVersion      = SSLv3 for client, all for server
TIMEOUTbusy     = 300 seconds
TIMEOUTclose    = 60 seconds
TIMEOUTconnect  = 10 seconds
TIMEOUTidle     = 43200 seconds
verify          = none
```
Excerpt of `/etc/apache-sys-proxy-ssl.conf`:
```
SSLProxyEngine on
SSLHonorCipherOrder on
SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECD$
SSLProtocol All -SSLv2 -SSLv3
SSLCertificateFile "/etc/stunnel/stunnel.pem"
SSLCertificateChainFile "/etc/stunnel/uca.pem"
```
`[/etc/stunnel] # ps aux |grep apache`
```
 3639 admin      2544 S < /usr/local/apache/bin/apache_proxy -k start -f /etc/apache-sys-proxy.conf
 3716 admin      2544 S < /usr/local/apache/bin/apache_proxy -k start -f /etc/apache-sys-proxy.conf
 4968 admin      2488 S < /usr/local/apache/bin/apache_proxy -k start -f /etc/apache-sys-proxy.conf
23649 admin       532 S   grep apache
24196 admin      3072 S   /usr/local/apache/bin/apache_proxys -k start -f /etc/apache-sys-proxy-ssl.conf
24486 admin      1780 S   /usr/local/apache/bin/apache-dav -k start -f /etc/apache-dav-sys.conf
24489 admin       888 S   /usr/local/apache/bin/apache-dav -k start -f /etc/apache-dav-sys.conf
24496 admin       816 S   /usr/local/apache/bin/apache-dav -k start -f /etc/apache-dav-sys.conf
24539 admin      2396 S   /usr/local/apache/bin/apache -k start -c PidFile /var/lock/apache.pid
24542 httpdusr   1224 S   /usr/local/apache/bin/apache -k start -c PidFile /var/lock/apache.pid
24543 httpdusr   1136 S   /usr/local/apache/bin/fcgi-p -k start -c PidFile /var/lock/apache.pid
24550 httpdusr   4188 S   /usr/local/apache/bin/apache -k start -c PidFile /var/lock/apache.pid
24551 httpdusr   4152 S   /usr/local/apache/bin/apache -k start -c PidFile /var/lock/apache.pid
24552 httpdusr   3592 S   /usr/local/apache/bin/apache -k start -c PidFile /var/lock/apache.pid
24784 admin      1476 S < /usr/local/apache/bin/apache_proxy -k start -f /etc/apache-sys-proxy.conf
24785 admin      1284 S < /usr/local/apache/bin/fcgi-pm      -k start -f /etc/apache-sys-proxy.conf
24989 admin      1352 S   /usr/local/apache/bin/apache_proxys -k start -f /etc/apache-sys-proxy-ssl.conf
24990 admin      1144 S   /usr/local/apache/bin/fcgi-pm       -k start -f /etc/apache-sys-proxy-ssl.conf
24993 admin      4712 S   /usr/local/apache/bin/apache_proxys -k start -f /etc/apache-sys-proxy-ssl.conf
25060 admin      4004 S   /usr/local/apache/bin/apache_proxys -k start -f /etc/apache-sys-proxy-ssl.conf
```
`[/etc/stunnel] # ps aux |grep stunnel`
`25216 admin       532 R   grep stunnel
`

/etc/init.d/stunnel.sh contains:
```
if [ -f $STUNNEL_UCA ]; then
  /bin/sed -i 's/^#SSLCertificateChainFile/SSLCertificateChainFile/g' $APACHE_PROXY$
fi
```
`[/etc/init.d] # lsof -i :443`
```
COMMAND   PID     USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
apache  24539    admin    5u  IPv4 34324981      0t0  TCP *:https (LISTEN)
apache  24543 httpdusr    5u  IPv4 34324981      0t0  TCP *:https (LISTEN)
apache  24550 httpdusr    5u  IPv4 34324981      0t0  TCP *:https (LISTEN)
apache  24551 httpdusr    5u  IPv4 34324981      0t0  TCP *:https (LISTEN)
apache  24552 httpdusr    5u  IPv4 34324981      0t0  TCP *:https (LISTEN)
```
`[/etc/init.d] # lsof -i :8080`
```
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
apache_pr  3639 admin    3u  IPv4  26718      0t0  TCP *:webcache (LISTEN)
apache_pr  3716 admin    3u  IPv4  26718      0t0  TCP *:webcache (LISTEN)
apache_pr  4968 admin    3u  IPv4  26718      0t0  TCP *:webcache (LISTEN)
apache_pr 24785 admin    3u  IPv4  26718      0t0  TCP *:webcache (LISTEN)
```

**Comment by Yannik** [comment]
Looks good to me! Are you still having issues?

**Comment by KurtTheBerner** [comment]
I got it, now I have Overal Rating A!
I had to add the following Entry in` /etc/config/apache/extra/httpd-ssl-vhosts-user.conf`:
`SSLCertificateChainFile "/etc/stunnel/uca.pem"`

Thanks again for your help

**Comment by Yannik** [comment]
@KurtTheBerner Great! Can you add your model and firmware version to this issue?

**Comment by KurtTheBerner** [comment]
Model: TS-251
Firmware: 4.2.0 Build 20151118

**Comment by ap2de** [comment]
Hello,
everything I add in  SSLCertificateChainFile "/etc/stunnel/uca.pem" as described by KurtTheBerner is being overwritten, when i add additional virtual servers in the QNAP Admin GUI.
How can I prevent this?

Thank you for your help 
AP2DE

**Comment by Yannik** [comment]
@ap2de You could check if there are any template files you could edit.
