### ISSUE TITLE
URL of cacert.pem was changed

### ISSUE THREAD

**Issue by rolfc** [Yannik/qnap-letsencrypt#100]
Hi, 
I wonder why my sha1sum won't match and I found the following:
`curl --silent https://curl.haxx.se/ca/cacert.pem | more`
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://curl.se/ca/cacert.pem">here</a>.</p>
<hr>
<address>Apache Server at curl.haxx.se Port 80</address>
</body></html>
```
Maybe you have to change the readme.md with the new url.
Thanks for the great small tool.

Best Regards
RolfC

**Comment by Yannik** [comment]
Thanks for the report, I've fixed this.
