### ISSUE TITLE
Installing problem

### ISSUE THREAD

**Issue by mvught** [Yannik/qnap-letsencrypt#101]
**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-859
Internal Model = TS-859
Version = 4.2.6
Build Number = 20210327
Rsync Model = QNAP
Build Date = 2021-03-27
```

**Is this the latest firmware for your device?**
YES
**Issue Summary (provide relevant error messages and log output):**
[/share/MD0_DATA/letsencrypt/qnap-letsencrypt] # ./renew_certificate.sh 
BusyBox v1.01 (2021.03.27-04:02+0000) multi-call binary

Usage: readlink 

Displays the value of a symbolic link.

Checking whether to renew certificate on Sat, 15 May 2021 20:33:14 +0200
Renewing certificate...
qnap-letsencrypt version: 21afc01
Using python path: python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 28029
Serving v4 only
Parsing account key...
Parsing CSR...
Found domains: datastore.localhome
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Traceback (most recent call last):
  File "/share/MD0_DATA/letsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/share/MD0_DATA/letsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/share/MD0_DATA/letsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 121, in get_crt
    order, _, order_headers = _send_signed_request(directory['newOrder'], order_payload, "Error creating new order")
  File "/share/MD0_DATA/letsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "/share/MD0_DATA/letsencrypt/qnap-letsencrypt/acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error creating new order:
Url: https://acme-v02.api.letsencrypt.org/acme/new-order
Data: b'{"protected": "eyJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImFsZyI6ICJSUzI1NiIsICJub25jZSI6ICIwMDAzM3plRVNwLUJFdFAzekxfWDBJNHM3bERzVUphcXRlN0hpaFRfQlJ5ajJKayIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8xMjM2MjM0OTAifQ", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiAiZG5zIiwgInZhbHVlIjogImRhdGFzdG9yZS5sb2NhbGhvbWUifV19", "signature": "etv1ICiOBsz-V3nf2HC6w8wX3b9Vm35CSJsuBFLgxDsLQG5oQ5wNhI7qvHYdvbEDFWWJBk-y0n2MQSOTUfPUfJ9RVVly_9YKQbTO-R6mZb5nI58qjc0vReLwX7dOuhpNQAdToLf1RBOZFrefeoT8VtY3xzBFkZWtfjsSG-QILVhYPdkX5yGy6YuO03EQKhUqicJ7KJWbFuA4H-ZFO8qOBTEY81NPEC_c7Y4SNqHG-9yUG6dgCYIyW8Fdvc1fhvt6UEKk6QXeP5cX4anwlBa5_LtDXFxPBEPe4wuVJsipljApSRO-KoYSyzZemFFljXwprr4l_zPFsHxU19E1Ybm1wTNdPYAWLRe91S-KRN0OaTx5pzNZkMziQG-MBlW65kORZrkx5mhw5V5cPwAoBZ8GmkZk9f9MbqFTdlBWOuZVfbdPKKa9uBDlCg4U0m_4y1Zyji7DVI1YikZn0lDdYnQFAOVqyWSh4818O4gbcxwoAbwRNNVNu4zqpopxIX3ROhCLcax8HKFqzYvsLR6AlOICdKhb-volewdXc7G5tu4Yl-nT6JLmPa3x6iThUd3kuhqKPcJzJfWowA4Q5nVfbAMctcc07EXSMtbFQYVWCnoY_Ow4wqX6zbxMgD6TMsriquGAlzQYqZaERILYMd9bnKC5mZ43eIkneFFOwEyUCTxEcQE"}'
Response Code: 400
Response: {'type': 'urn:ietf:params:acme:error:rejectedIdentifier', 'detail': 'Error creating new order :: Cannot issue for "datastore.localhome": Domain name does not end with a valid public suffix (TLD)', 'status': 400}
An error occured. Restoring system state.
./renew_certificate.sh: line 11: 28029 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/MD0_DATA/letsencrypt/qnap-letsencrypt/tmp-webroot)
[/share/MD0_DATA/letsencrypt/qnap-letsencrypt] # 

Need some help with the last steps ./renew_certificate.sh ? "see log above"

**Comment by aetasoul** [comment]
You are asking for a public certificate for a private domain.
These are two distinct “systems” with distinct choices (choose one per domain):

*  Use a private certificate [private CA] for a private domain.
*  Use a public certificate [LetsEncrypt] for a public domain.
