### ISSUE TITLE
Update fails because of quFirewall blocking access

### ISSUE THREAD

**Issue by viollinn** [Yannik/qnap-letsencrypt#102]
**Platform/Firmware Information**

```
Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-253Be

Model = TS-X53B
Internal Model = TS-X53B
Version = 4.5.3
Build Number = 20210515
Rsync Model = QNAP
Build Date = 2021-05-15
```
I tried to run the script and it kept failing until i realized quFirewall was running.
After stoping it, all went smoothly again.

Would it be possible to stop quFirewall before renewal and start it after ?

**Comment by aetasoul** [comment]
I think disable qufirewall from the script can cause some security issue, maybe is better to create a new profile on your qufirewall to allow the traffic TCP/UDP on the port 80 from letsencrypt?

**Comment by viollinn** [comment]
Setting a new profile won't work as letsencrypt don't publish a list of IP's or domain name's as stated here: https://certbot.eff.org/faq#what-ip-addresses-will-the-let-s-encrypt-servers-use-to-validate-my-web-server

**Comment by Yannik** [comment]
I agree with @aetasoul, adding a firewall rule tcp/udp on port 80 (possibly from the script, and removing it afterwards?) does seem to be the better solution (in comparison to completely disabling the firewall during script runs).
