### ISSUE TITLE
After apply to the new certificate, the SSL connection won't work. Without error

### ISSUE THREAD

**Issue by itemx** [Yannik/qnap-letsencrypt#104]
**Platform/Firmware Information**

Platform = X86_SUMMITRIDGE
DISPLAY_NAME = TS-1277
Model=TS-X77
Internal Model = TS-X77
Version = 4.5.4
Build Number = 20210630
Rsync Model = QNAP
Build Date = 2021-06-30

**Is this the latest firmware for your device?**

NO, But planned to update to the latest 4.5.4

**Issue Summary (provide relevant error messages and log output):**

If I roll back to the system default certificate, the SSL connection will work.
However, if I run the renew_certificate, the SSL port will become unavailable.
It was working earlier, so not certain what's going on.
The QNAP support suggests rolling back to default, and the service will back - without a valid certification.
Does not see any errors from the console, do you have any suggestions?

[/share/homes/cert/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Tue, 13 Jul 2021 11:52:16 +0800
Renewing certificate...
qnap-letsencrypt version: 21afc01
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 23790
Parsing account key...
Parsing CSR...
Found domains: xxx.myqnapcloud.com, xxx.another.domain
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying xxx.another.domain...
::ffff:125.227.223.5 - - [13/Jul/2021 11:52:31] "GET /.well-known/acme-challenge/oR0sC9JE40cyj9mdjZUJCppTl1bUle0VrmeHX8Xxs9Q HTTP/1.1" 200 -
xxx.another.domain verified!
Verifying xxx.myqnapcloud.com...
::ffff:125.227.223.5 - - [13/Jul/2021 11:52:35] "GET /.well-known/acme-challenge/YcP1V95sD6MqKMpYsvpyI2baxHdFnhtNogLC6SCNCiA HTTP/1.1" 200 -
xxx.myqnapcloud.com verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
GnuTLS: Resource temporarily unavailable, try again.
2021-07-13 11:52:44 URL:https://letsencrypt.org/certs/lets-encrypt-r3-cross-signed.pem [1586/1586] -> "-" [1]
Stopping stunnel and setting new stunnel certificates...
Shutting down apache proxy: OK
Restarting FTP
Shutting down FTP services: ..OK
Starting FTP services: OK
Done! Service startup and cleanup will follow now...
./renew_certificate.sh: line 11: 23790 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/homes/cert/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Starting Qthttpd services: OK
[/share/homes/cert/qnap-letsencrypt] # curl https://xxx.another.domain
curl: (7) Failed to connect to xxx.another.domain port 443: Connection refused
[/share/homes/cert/qnap-letsencrypt] # curl https://xxx.myqnapcloud.com
curl: (7) Failed to connect to xxx.myqnapcloud.com port 443: Connection refused

**Comment by Yannik** [comment]
@itemx Any results on this? Ultimately, you will need to examine your webserver config and logs to find out what is going wrong here.

**Comment by itemx** [comment]
No luck after checking with QNAP supports. At the moment they suggest me to use the built-in letsencrypt service and it somehow works even with multiple domains.


I still have some QNAP NAS using the qnap-letsencrypt and it still working. Will keep eyes on them.
