### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by alexlomas** [Yannik/qnap-letsencrypt#11]
A total edge case I'm sure, but I came across this now that letsencrypt support IPv6:

The python SimpleHTTPServer seems to listen on v4 only. I worked around this by starting the internal QWeb server then editing the init.sh / renew.sh scripts to point at a world-readable directory under /share/QWeb instead of running its own python web server. Seems to work fine.

**Comment by Yannik** [comment]
Thanks for documenting this!
