### ISSUE TITLE
cannot verify letsencrypt.org's certificate

### ISSUE THREAD

**Issue by ash73** [Yannik/qnap-letsencrypt#114]
**Platform/Firmware Information**

Platform = MARVELL_6281
Model = TS-110
Internal Model = TS-119
Version = 4.2.5
Build Number = 20170413
Rsync Model = QNAP
Build Date = 2017-04-13

**Is this the latest firmware for your device?**

Yes, but legacy

**Issue Summary (provide relevant error messages and log output):**

After working fine for ages, the script is now failing to verify the certificate as follows:

Renewing certificate...
qnap-letsencrypt version: bbcb28b
Using python path: /share/HDA_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 4368
Serving v4 only
Parsing account key...
Parsing CSR...
Found domains: mydomain.ddns.net
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying mydomain.ddns.net...
192.168.5.10 - - [17/Dec/2021 13:17:56] "GET /.well-known/acme-challenge/1gHVd3XjsYnEQQ4SuvZHAsZk94dF-M94k6hI9j3HgEE HTTP/1.1" 200 -
mydomain.ddns.net verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
ERROR: cannot verify letsencrypt.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to letsencrypt.org insecurely, use `--no-check-certificate'.
An error occured. Restoring system state.
Start apache proxy: OK
Starting Qthttpd services: OK

**Comment by Yannik** [comment]
Please try updating your cacert.pem

**Comment by ash73** [comment]
Thanks for the reply, how do I do that?

**Comment by Yannik** [comment]
https://github.com/Yannik/qnap-letsencrypt#setting-up-a-valid-ca-bundle-and-cloning-this-repo

**Comment by ash73** [comment]
Deleted the whole lot and reinstalled, still get the same error. Now I get "too many certificates issued" will try again tomorrow.

**Comment by ash73** [comment]
I think it might have to do with this:
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

According to my log file the certificate renewal first failed in Nov.

Any way to fix this on a legacy QNAP?

**Comment by Yannik** [comment]
Have you updated qnap-letsencrypt to the latest commit? 

I think what you linked has been fixed in https://github.com/Yannik/qnap-letsencrypt/commit/0ecdfdd211040369f310142f6925f060c5d61fa6 and https://github.com/Yannik/qnap-letsencrypt/commit/4a85d41096a8198b318b8e2afa062290f9323938

**Comment by ash73** [comment]
With the latest version I get this:

BusyBox v1.01 (2017.04.12-18:47+0000) multi-call binary

Usage: readlink

Displays the value of a symbolic link.

Checking whether to renew certificate on Mon, 20 Dec 2021 22:33:50 +0000
Renewing certificate...
qnap-letsencrypt version: 452dc7d
Using python path: /share/HDA_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 2903
Serving v4 only
Parsing account key...
Parsing CSR...
Found domains: mydomain.ddns.net
Getting directory...
Directory found!
Registering account...
Already registered! Account ID: https://acme-v02.api.letsencrypt.org/acme/acct/326835790
Creating new order...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "acme-tiny/acme_tiny.py", line 120, in get_crt
    order, _, order_headers = _send_signed_request(directory['newOrder'], order_payload, "Error creating new order")
  File "acme-tiny/acme_tiny.py", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error creating new order:
Url: https://acme-v02.api.letsencrypt.org/acme/new-order
Data: b'{"protected": "eyJub25jZSI6ICIwMDAyWnpXQTZpdVEwT2Z4bHFOT1NIRFI5bFVnb3RkSzdyZ0U0M00tVGxlQWlRRSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC8zMjY4MzU3OTAifQ", "payload": "eyJpZGVudGlmaWVycyI6IFt7InZhbHVlIjogImhhc3NhbGxjYXN0bGUuZGRucy5uZXQiLCAidHlwZSI6ICJkbnMifV19", "signature": "FllsPxU1eLeFLGUzBSpwgCDGYlU6wmMbViStmZaoCXIce486_zkbeYIfk3Hw0G1AZO8oMjMz3YOE1s7P-WnsMBstO8EgabNb8HoRCXkhpaGKULHJE1iADIxsc6rrldNr8IaSrZ1y4c3j6LBbbpT7OVRNOHtNNLiVLzr2MpR0hbwTzpGObjSTw8357F7AzZg_TQB3HCAN34AVTYoPW1fm02Wc4azfW3DU-hx9quj9wpxyjbiTz4rvP-8_clGE7dMJhCVZMb2a-Dn5IsiOQDmPuOqqp0X6DQ9OOiEm2rkOHWDaUtePSLI67ywDxQA3B8x62njx83PYI-BLoak59KFLcayugBJRM4kFyJtSiRwtdEuNBCybMbul8CVk04zBLGVzcpZ9P9wSg11frX-YpjSGHBBnOD0L5Xzbc7UN7ZwqYEfXhSDUqwWcWbWKeKWKpi5kLT6DiEH1p7nmvbPwYh7Y80Y0QFLleh2Nt9vmLhs5hVh_YuQxRsg51vn4XPUrB2QxQh6t1-cm3Mty1pQoh1SHDeYrxAcNIBpm86_8w7yYn6R6VdTusQvICD3EYq2FN1zil_ku_di3MbilJ55uKfltdO-74VBTj-EW6oSubISzNK4PxVNpHY5zBga2hxBT7aPWpm0G8UGrxR6ivXhkUgzImsJInDb7r3sNL8LRKbBc6Ws"}'
Response Code: 429
Response: {'status': 429, 'type': 'urn:ietf:params:acme:error:rateLimited', 'detail': 'Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mydomain.ddns.net: see https://letsencrypt.org/docs/rate-limits/'}
An error occured. Restoring system state.
Start apache proxy: OK
Starting Qthttpd services: OK

**Comment by Yannik** [comment]
Well, it says in the error message that you are rate limited. 

According to https://letsencrypt.org/docs/rate-limits/

> Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a Duplicate Certificate limit of 5 per week. Exceeding the Duplicate Certificate limit is reported with the error message too many certificates already issued for exact set of domains.

It's best to try again in a week when the rate limit has been reset.
