### ISSUE TITLE
Setup let's qnap-encrypt, renew_certificate.sh issue

### ISSUE THREAD

**Issue by chapit-nicolas** [Yannik/qnap-letsencrypt#116]
**Platform/Firmware Information**

Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-453Be
Model = TS-X53B
Internal Model = TS-X53B
Version = 5.0.0
Build Number = 20220129
Rsync Model = QNAP
Build Date = 2022-01-29

**Is this the latest firmware for your device?** YES

**Issue Summary (provide relevant error messages and log output):**
Hi, I tried to setup your code on my Qnap, but when I ran renew_certificate.sh, I got this:
![Screenshot from 2022-03-30 17-19-52](https://user-images.githubusercontent.com/13436237/160933632-3271e0d5-aeed-4061-aae0-0174c17ce5ca.png)

Python installed (through App Store) v3.5.2.0.1

So maybe, I forgot to install something. 

The previous steps were done with success, except step 2 for the setup. I had to generate the .rnd file.
Any clue what's going on?

Thanks.

**Comment by Yannik** [comment]
I'd suggest search for the error message that you got: https://github.com/Yannik/qnap-letsencrypt/issues?q=unknown+url+type
