### ISSUE TITLE
Renew Certificate not possible

### ISSUE THREAD

**Issue by LeukoClassic** [Yannik/qnap-letsencrypt#12]
Hi,
I installed lets encrypt on my qnap without any problems.
But now after a month I get an error using the renew_certificate.sh
and I dont understan why. The cirtificate already expired and I hope
I can fix it quickly with your help.

The error is:

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/wdi0JYjORbsJTedrAfSInMbpaPVz0i2vfyrXKtglU-8, but couldn't download http://***SERVER-URL***/.well-known/acme-challenge/wdi0JYjORbsJTedrAfSInMbpaPVz0i2vfyrXKtglU-8
 
Thanks for the help
Greetings
LeukoClassic

**Comment by Yannik** [comment]
hm, check if the python webserver starts properly and if it is reachable from outside your local network.

**Comment by LeukoClassic** [comment]
Hi,
I changed the port in the renew script and set a new port forwarding to the router and tested it from outside of my lan. But the error seams to be the same. Here is the complete log after starting the renew sequence:


Checking whether to renew certificate on Thu, 04 Aug 2016 19:25:11 +0200
Renewing certificate...
Stopping Qthttpd hogging port ...
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 11271 
Serving HTTP on 0.0.0.0 port 8000 ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying **ServerURL**
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/pSPklgzc84G6zSx3qNqMEjP0POC1Ty9GC-L3vCnCKVw, but couldn't download http://**ServerURL**/.well-known/acme-challenge/pSPklgzc84G6zSx3qNqMEjP0POC1Ty9GC-L3vCnCKVw

**Comment by Yannik** [comment]
needs to be reachable on port 80 from outside iirc.

**Comment by LeukoClassic** [comment]
Oh damn..my fault!
Ok that solved the problem.
Thank you very much:)
