### ISSUE TITLE
Error when renewing certificate

### ISSUE THREAD

**Issue by aski71** [Yannik/qnap-letsencrypt#125]
**Platform/Firmware Information**

```

Platform = X86_PINEVIEW
Model = TS-459
Internal Model = TS-459
Version = 4.2.6
Build Number = 20221028
Rsync Model = QNAP
Build Date = 2022-10-28

```

**Is this the latest firmware for your device?** yes

**Issue Summary (provide relevant error messages and log output):**

Certificate can no longer be renewed.

`[/share/MD0_DATA/letsencrypt/qnap-letsencrypt] # ./renew_certificate.sh                                                                                                               
Checking whether to renew certificate on Sun, 29 Jan 2023 22:35:00 +0100
Renewing certificate...
./renew_certificate.sh: line 42: git: command not found
qnap-letsencrypt version: 
Using python path: /share/MD0_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
xargs: invalid option -- I
BusyBox v1.01 (2022.10.27-23:57+0000) multi-call binary

Usage: xargs [COMMAND] [OPTIONS] [ARGS...]

Executes COMMAND on every item given by standard input.

Options:
	-r	Do not run command for empty readed lines
	-x	Exit if the size is exceeded
	-0	Input filenames are terminated by a null character
	-t	Print the command line on stderr before executing it.

An error occured. Restoring system state.
Start apache proxy: OK
Starting Qthttpd services: OK
`

**Comment by Yannik** [comment]
What is the output of `xargs --help` and `which xargs` on your qnap?

**Comment by aski71** [comment]
BusyBox v1.01 (2022.10.27-23:57+0000) multi-call binary

Usage: xargs [COMMAND] [OPTIONS] [ARGS...]

Executes COMMAND on every item given by standard input.

Options:
	-r	Do not run command for empty readed lines
	-x	Exit if the size is exceeded
	-0	Input filenames are terminated by a null character
	-t	Print the command line on stderr before executing it.


/usr/bin/xargs

Just as additional information: I'm using this machine only as a remote backup target. I change nothing on it except that every once in a while I install a security upgrade. It has been working for many years. I haven't touched the system for at least half a year. So I'm a bit confused why xargs should have been changed. :-)

Thanks for your help.

**Comment by aski71** [comment]
Might the issue be further up? 
It also says: git command not found.
I see python 2.7.3 and python 3.5.0.2 installed as packages.

**Comment by aski71** [comment]
AH! Found it!
git was installed as part of Entware.
Entware was stopped for whatever reason.
After I started Entware again, renew_certificate.sh was running through smoothely.
Thanks anyway!
