### ISSUE TITLE
Multiple Subdomains

### ISSUE THREAD

**Issue by silencshadow** [Yannik/qnap-letsencrypt#13]
Hello,

Is there a work Around to add/create multiple certs for subdomains? Like www.maindomain.com got the cert but the cert on www.sub.maindomain.com is wrong ..

Regards

**Comment by Yannik** [comment]
there is a description how to create a multi domain cert here:
https://github.com/Yannik/qnap-letsencrypt#setting-up-qnap-letsencrypt

**Comment by itemx** [comment]
When deploy, I found I'll receive error

Error Loading request extension section SAN

if I just copy and paste provided commands in multiple domain.
--
cd letsencypt
cp ../openssl.cnf openssl-csr-conf.cnf
printf "subjectAltName=DNS:nas.xxx.de,DNS:nas.xxx.com" >> openssl-csr-config.cnf
openssl req -new -sha256 -key keys/domain.key -subj "/" -reqexts SAN -config openssl-csr-config.cnf > domain.csr
--
After look through the command, I believe there's a typo to cause this:
We copied a file named "openssl-csr-conf.cnf" but later we append subjectAltName to "openssl-csr-conf[IG].cnf"

Not a big issue, but it will be nice if can modify the command to make them work without pain.

**Comment by Yannik** [comment]
thanks, fixed!
