### ISSUE TITLE
Cannot clone repo onto QNAP

### ISSUE THREAD

**Issue by crumdev** [Yannik/qnap-letsencrypt#15]
**Platform/Firmware Information**
Platform = X86_BRASWELL
DISPLAY_NAME=TS-453A
Model = TS-X53II
Internal Model = TS-X53II
Version = 4.2.2
Build Number = 20160901
Rsync Model = QNAP
Build Date = 2016-09-01

```
Run
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["

and paste it here!
```

**Is this the latest firmware for your device?** YES

**Issue Summary (provide relevant error messages and log output):**

```
[/share/Web/ssl_cert] # git config --system http.sslVerify true
[/share/Web/ssl_cert] # git config --system http.sslCAinfo `pwd`/cacert.pem
[/share/Web/ssl_cert] # git config --get http.sslVerify
true
[/share/Web/ssl_cert] # git config --get http.sslCAinfo
/share/Web/ssl_cert/cacert.pem
[/share/Web/ssl_cert] # git clone https://github.com/Yannik/qnap-letsencrypt.git
Cloning into 'qnap-letsencrypt'...
fatal: unable to access 'https://github.com/Yannik/qnap-letsencrypt.git/': SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[/share/Web/ssl_cert] #
```

**Comment by itemx** [comment]
I met same problem before and my workaround is set

git config --system http.sslVerify false

git will not check ssl certification so you can clone normally.
However I am not certain why we're unable to verify it....

**Comment by Yannik** [comment]
@crumdev What's the output of `ls -alsh /share/Web/ssl_cert/cacert.pem`

**Comment by itemx** [comment]
@Yannik 
Inspired by your comment, I checked my cacert.pem and figure out the content inside is
`[/share/homes/cert/qnap-letsencrypt] # cat cacert.pem
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://curl.haxx.se/ca/cacert.pem">here</a>.</p>
<hr>
<address>Apache Server at curl.haxx.se Port 80</address>
</body></html>
[/share/homes/cert/qnap-letsencrypt] #
`

Well maybe we need to update the path to download cacert.pem ?

**Comment by Yannik** [comment]
@itemx Definitely! Perhaps you can fix this and open a PR?

**Comment by crumdev** [comment]
```
[~] # cd /share/Web/ssl_cert/
[/share/Web/ssl_cert] # ls -alsh /share/Web/ssl_cert/cacert.pem
 256 -rw-r--r--    1 admin    administ    255.5k Sep  6 23:12 /share/Web/ssl_cer                                                            t/cacert.pem
```

I also tried the location the document was moved to. Confirmed that doing using cat cacert.pem showed the certificates. Still got this error.

```
[/share/Web/ssl_cert] # git clone https://github.com/Yannik/qnap-letsencrypt.git
Cloning into 'qnap-letsencrypt'...
fatal: unable to access 'https://github.com/Yannik/qnap-letsencrypt.git/': SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by itemx** [comment]
Does not have time to check in detail, but in my case after re-download the cacert.pem helps a little, but still receives errors.

> [/share/homes/cert/qnap-letsencrypt] # ls -alsh /share/homes/cert/qnap-letsencrypt/cacert.pem
>  256 -rw-rw----    1 admin    administ    255.5k Sep  7 11:12 /share/homes/cert/qnap-letsencrypt/cacert.pem
> [/share/homes/cert/qnap-letsencrypt] # git pull
> fatal: unable to access 'https://github.com/Yannik/qnap-letsencrypt.git/': SSL certificate problem, verify that the CA cert is OK. Details:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> 

And my system is

> Platform = X86_STEPPEEAGLE
> DISPLAY_NAME=TVS-663
> Model = TS-X63
> Internal Model = TS-X63
> Version = 4.2.2
> Build Number = 20160901
> Rsync Model = QNAP
> Build Date = 2016-09-01
>

**Comment by Yannik** [comment]
@crumdev @itemx Can you double check the location and permission of the certificate and the git options. Generally if you downloaded the correct cert bundle this should definitely work now.

**Comment by itemx** [comment]
@Yannik 
The cacert.pem itself seems OK.
(I added -k to ignore ssl verification for curl anyway)

```
[/share/homes/cert/qnap-letsencrypt] # curl -k -s https://curl.haxx.se/ca/cacert.pem | sha1sum
df8ee25ac701031c3a6100a253caf8dca0c1a63b  -
[/share/homes/cert/qnap-letsencrypt] # sha1sum cacert.pem
df8ee25ac701031c3a6100a253caf8dca0c1a63b  cacert.pem
[/share/homes/cert/qnap-letsencrypt] #
```

For the permission, will I have to add read permission for everyone? (aka 644 for .prm file)
btw my git is 2.1.0 (qpkg version) is that same as what you have on your environment?

**Comment by Yannik** [comment]
@itemx Yep, same git version here. Your sha1sum seems to be correct as well.

**Comment by Yannik** [comment]
@itemx I never had to set permissions but you can try just to eliminate this as a cause.

**Comment by itemx** [comment]
@Yannik sorry just busy yesterday. 
I tried to add read permission to cacert.pem, but seesm the result is the same.
No idea which config should I check further in this moment.

```
[/share/homes/cert/qnap-letsencrypt] # git pull
fatal: unable to access 'https://github.com/Yannik/qnap-letsencrypt.git/': SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
[/share/homes/cert/qnap-letsencrypt] # git config --system -l
http.sslverify=true
http.sslcainfo=/share/homes/cert/qnap-letsencrypt/cacert.pem
[/share/homes/cert/qnap-letsencrypt] # ls -al
...
-rw-rw-r--    1 admin    administ    261618 Sep  7 11:12 cacert.pem
...

[/share/homes/cert/qnap-letsencrypt] #
```

**Comment by Yannik** [comment]
@itemx @crumdev I was able to reproduce this issue. With the former cacert.pem I had saved, the clone worked flawlessly. With the new cacert.pem from curl.haxx.se, the same issue as you are having. Any ideas what could be the cause?

**Comment by Yannik** [comment]
Check out if this cacert.pem works for you: https://curl.haxx.se/ca/cacert-2016-01-20.pem

**Comment by tsander** [comment]
Old cert above worked fine. New cert does not for me.

**Comment by roduts** [comment]
hi, I managed to git clone :D,
replace https with git and it works, replace it also in init.sh

**Comment by Yannik** [comment]
Just checked, this works with the latest cacert.pem from curl.haxx.se. There must've been an issue on there side before.
