### ISSUE TITLE
renew_certificate.sh nukes virtual hosts

### ISSUE THREAD

**Issue by guppy42** [Yannik/qnap-letsencrypt#2]
After completeing the renew_certificate step all virtual hosts are gone, the web server is disabled and cannot be re-enabled as changes cannot be saved.

attempts to do so via the Qnap web interface are met with "failed to apply the changes".

**Comment by Yannik** [comment]
`renew_certificate.sh` does not modify any virtual hosts.
Please provide additional information regarding this issue, including model and firmware version.

**Comment by guppy42** [comment]
Qnap TS-419P II ( just updated to firmware 4.2 today )

only error was that it couldn't download the file it created - that domain maps to a different port ( 443->8082 )

In desperation I tried rebooting - now the administration interface is not working either. (getting ERR_CONNECTION_REFUSED )

luckily ssh still works, please advice how I can fix this :(

**Comment by guppy42** [comment]
Ohkay.. got everything back now with;
```
# mv /etc/stunnel/stunnel.pem /etc/stunnel/stunnel.pem.letsencrypt
# cp /etc/stunnel/stunnel.pem.orig /etc/stunnel/stunnel.pem
# /etc/init.d/stunnel.sh restart
```


clearly something is wrong with the generated stunnel.pem - it looks fine tho?

**Comment by Yannik** [comment]
Is your QNAP using apache or stunnel for tls?

Please compare the permissions of each stunnel.pem file, maybe it can't be read. I will need more information about the errors in your apache/stunnel log to help you.

**Comment by guppy42** [comment]
> Is your QNAP using apache or stunnel for tls?

How do I check that?

> Please compare the permissions of each stunnel.pem file, maybe it can't be read. I will need more information about the errors in your apache/stunnel log to help you.

As I recall the only major discrepancy was that the new stunnel.pem file was roughly twice as big.

My QNAP seems to be back in working order now, but please let me know if there is any information I can provide you that will help figuring out the issue.

**Comment by Yannik** [comment]
Please
 * double check that /etc/stunnel/stunnel.pem contains `letsencrypt/keys/domain.key`, `letsencrypt/signed.crt` and `letsencrypt/intermediate.pem`
 * check non-corruption of your certs/keys:

  ```
   openssl rsa -in keys/domain.key -check
   openssl x509 -in signed.crt -text -noout
   openssl x509 -in intermediate.pem -text -noout
```
 * Post your `stunnel.conf` here
 * Post the output of `stunnel -version`
 * Post what's in your `apache-sys-proxy-ssl.conf`
 * Output of `ps aux |grep apache` and `ps aux |grep stunnel`
 * Output of `lsof -i :443` and `lsof -i:8080`

**Comment by guppy42** [comment]
/etc/stunnel/stunnel.pem contains
letsencrypt/keys/domain.key - yes
letsencrypt/signed.crt - 0 bytes long 
letsencrypt/intermediate.pem - yes


signed.crt being 0 bytes long is properly the heart of the issue, and I'm guessing that the reason is that it could not fetch the .wellknown file since the domain that I used is portforwarded to a different port that then one the python server listens to.

This is down to my own stupidity for not reading though the instructions beforehand, but it could also happen if you misspell the domain name - so maybe a check that if the obtained certificate is 0 bytes don't attempt to install it?


manually running the lines from python acme-tiny/acme_tiny.py [..] to the echo line works fine with specifying the correct path, now I just need to figure out where to store the resulting certificate so it works with the apache vhosts - and ofcourse create a new renew script. :)

**Comment by Yannik** [comment]
Now checking whether signed.crt is empty is done and the script will exit early if any errors occur (especially useful if errors occur during the letsencrypt cert generation).

> manually running the lines from python acme-tiny/acme_tiny.py [..] to the echo line works fine with specifying the correct path, now I just need to figure out where to store the resulting certificate so it works with the apache vhosts - and ofcourse create a new renew script. :)

I am not sure what the issue with the provided renew script is?

**Comment by guppy42** [comment]
I'm sure it's fine but I need to specify the path to the .well-known directory to make sure it can be checked since It's running from /share/web/mydomain/ and on a nonstandart port that's being forwarded by the router. 


IE.  Mydomain.com is forwarded to eg. port 8082 on the qnap so starting a python webserver on port 80 means it won't be visible.

If that makes sense?

**Comment by Yannik** [comment]
Are you behind a NAT and forwarding port 80 of your public IP to port 8082 of the NAS? Because I assume this will be necessary, as the .well-known approach only works on port 80.

**Comment by guppy42** [comment]
Correct, the router forwards port 80 (and 443 ) to different ports on the NAS based on domain name.
