### ISSUE TITLE
Verification fails

### ISSUE THREAD

**Issue by voodoomatz** [Yannik/qnap-letsencrypt#20]
**Platform/Firmware Information**
Platform = X86_BAYTRAIL
DISPLAY_NAME=TS-453mini
Model = TS-X53
Internal Model = TS-X53
Version = 4.2.2
Build Number = 20161214
Rsync Model = QNAP
Build Date = 2016-12-14

**Is this the latest firmware for your device?**
YES

**Issue Summary (provide relevant error messages and log output):**
Upon running renew_certificate.sh I get this:
[/share/CACHEDEV1_DATA/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Thu, 05 Jan 2017 19:37:17 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 31267
Serving HTTP on 0.0.0.0 port 80 ...
Parsing account key...
Parsing CSR...
Registering account...
Registered!
Verifying xxx.test.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/WcuDg2mIznrSjOm_XzgZqFquYeNi_YgAoD-E1GTzlBE, but couldn't download http://xxx.test.com/.well-known/acme-challenge/WcuDg2mIznrSjOm_XzgZqFquYeNi_YgAoD-E1GTzlBE

**Comment by mkorte** [comment]
Ok, I found the solution. Port 80 wasn't forwarded to my QNAP.
I don't know what to make of this. I don't really want to expose port 80 to the Web.

**Comment by Yannik** [comment]
Well, you could forward the external port 80 to an internal port that is only used by letsencrypt, this will, except when letsencrypt is running, port 80 is not reachable from the web.
