### ISSUE TITLE
ERROR: cannot verify qbox4u.com's certificate, issued by ‘/C=US/O=Let's Encrypt

### ISSUE THREAD

**Issue by qbox4u** [Yannik/qnap-letsencrypt#22]
Dear Yannik,

The setup works fine, but retrieving files from my server by another server by wget gives an issue
ERROR: cannot verify qbox4u.com's certificate

Platform = X86_PINEVIEW

Model = TS-459
Internal Model = TS-459
Version = 4.2.2
Build Number = 20161214
Rsync Model = QNAP
Build Date = 2016-12-14

**Is this the latest firmware for your device?**
yep

**Issue Summary (provide relevant error messages and log output):**
_[~] # wget https://qbox4u.com:8081/nonconf/qnap_install_resources/read.me
--2017-01-10 07:06:49--  https://qbox4u.com:8081/nonconf/qnap_install_resources/read.me
Resolving qbox4u.com (qbox4u.com)... 1.173.96.248
Connecting to qbox4u.com (qbox4u.com)|1.173.96.248|:8081... connected.
ERROR: cannot verify qbox4u.com's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3’:
  Unable to locally verify the issuer's authority.
To connect to qbox4u.com insecurely, use `--no-check-certificate'.
[~] #_

**Comment by Yannik** [comment]
Does `wget https://icanhazip.com` work?

**Comment by qbox4u** [comment]
Case solved.  Is an issue with opkg.
