### ISSUE TITLE
script  renewcertificate.sh fails

### ISSUE THREAD

**Issue by roduts** [Yannik/qnap-letsencrypt#23]
Platform = X86_BAYTRAIL
DISPLAY_NAME=TS-251
Model = TS-X51
Internal Model = TS-X51
Version = 4.2.2
Build Number = 20161214
Rsync Model = QNAP
Build Date = 2016-12-14

when running:
python acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir tmp-webroot/.well-known/acme-challenge > letsencrypt/signed.crt

i get:
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying websiteurl.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/AcB_wlEVls46CnasI9fvc0Mhr13y3k0l1CfORy1ODyw, but couldn't download http://websiteurl.com/.well-known/acme-challenge/AcB_wlEVls46CnasI9fvc0Mhr13y3k0l1CfORy1ODyw

**Comment by Yannik** [comment]
Your nas is not reachable under the domain you are trying to validate.
