### ISSUE TITLE
checksums don't match anymore

### ISSUE THREAD

**Issue by davebooi** [Yannik/qnap-letsencrypt#24]
Hi there,

seems as if the checksums don't match anymore

This is what I get from the server: **da39a3ee5e6b4b0d3255bfef95601890afd80709**

This is what I get after wget: **66fcd716fe1abb861bfd8b108655164b92d57489**

Strangely wget checks for the certificate despite the option not to:

`wget --no-check-certificate https://curl.haxx.se/ca/cacert.pem
2017-01-26 14:31:58--  https://curl.haxx.se/ca/cacert.pem
Resolving curl.haxx.se... 80.67.6.50, 2a00:1a28:1200:9::2
Connecting to curl.haxx.se|80.67.6.50|:443... connected.
WARNING: cannot verify curl.haxx.se's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3’:
Unable to locally verify the issuer's authority.`

Using wget in version 1.16

Cheers

**Comment by Yannik** [comment]
Looks like your connection has been compromised. Do you still need help with this? Otherwise I'll close this issue.

**Comment by davebooi** [comment]
It is no longer relevant to me, hence you can close this issue.
