### ISSUE TITLE
urllib2.URLError: <urlopen error unknown url type: https>

### ISSUE THREAD

**Issue by Pivert** [Yannik/qnap-letsencrypt#26]
**Platform/Firmware Information**
Platform = ARM_MS
DISPLAY_NAME=TS-231
Model = TS-X31
Internal Model = TS-X31
Version = 4.2.3
Build Number = 20170121
Rsync Model = QNAP
Build Date = 2017-01-21

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
It seems that the default urllib2 does not support SSL, and from the acme-tiny/acme_tiny.py we can read:
DEFAULT_CA = "https://acme-v01.api.letsencrypt.org"
the http version is anyway a redirect to the https version.

**Trace:**
[/share/CACHEDEV1_DATA/qnap-letsencrypt] # ./renew_certificate.sh 
Checking whether to renew certificate on Wed, 08 Feb 2017 13:19:00 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 18286
Serving HTTP on 0.0.0.0 port 80 ...
Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 85, in get_crt
    "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
  File "acme-tiny/acme_tiny.py", line 47, in _send_signed_request
    protected["nonce"] = urlopen(CA + "/directory").headers['Replay-Nonce']
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 423, in _open
    'unknown_open', req)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/lib/python2.7/urllib2.py", line 1240, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>

**Comment by chridi89** [comment]
Hello Pivert,

i had the same Issue, a good workarroud is to change the Line 21 of the renew_certificate.sh from
`python acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir tmp-webroot/.well-known/acme-challenge > letsencrypt/signed.crt`
to
`python2 acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir tmp-webroot/.well-known/acme-challenge > letsencrypt/signed.crt`
for me this works without any problems.

Regards
Christopher

**Comment by Yannik** [comment]
yeah, this indicates a problem with your python setup.
