### ISSUE TITLE
Error while running cron job, but ok with manually executes shell script

### ISSUE THREAD

**Issue by kynwu** [Yannik/qnap-letsencrypt#27]
**Platform/Firmware Information**
Platform = MARVELL_6281
Model = TS-220
Internal Model = TS-219
Version = 4.2.2
Build Number = 20160901
Rsync Model = QNAP
Build Date = 2016-09-01

**Is this the latest firmware for your device?**
NO
**Issue Summary (provide relevant error messages and log output):**
I have following line in my crontab config:
```
30 3 * * * cd /share/MD0_DATA/letsencrypt/qnap-letsencrypt/ && ./renew_certificate.sh >> ./renew_certificate.log 2>&1
```

when the cron job executes, I always get following error:
```
Checking whether to renew certificate on Sat, 25 Feb 2017 03:30:01 +0800
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 15507
/usr/local/bin/python2.7: No module named SimpleHTTPServer
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 2, in <module>
    import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
  File "/root/daily_build/4.2.2/Model/TS-220/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/argparse.py", line 85, in <module>
ImportError: No module named collections
```

But if I start renew_certificate.sh by **./renew_certificate.sh** by myself. Everything seems to be good!
What's wrong with my situation?

**Comment by Yannik** [comment]
i guess you are using a different python version. try specifying the full python path.
