### ISSUE TITLE
problem with verifying account

### ISSUE THREAD

**Issue by UserX82** [Yannik/qnap-letsencrypt#28]
**Platform/Firmware Information**
Platform = MARVELL_6281
Model = TS-420
Internal Model = TS-419
Version = 4.2.2
Build Number = 20161214
Rsync Model = QNAP
Build Date = 2016-12-14

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
need some help to find and solve that issue (replaced my domain with "x....x")

```
sh renew_certificate.sh
Checking whether to renew certificate on Sun, 19 Mar 2017 12:08:13 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 28114
Serving HTTP on 0.0.0.0 port 80 ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying x....x.noip.me...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/Eb0HflEdcibYcb-1lbR9QRa7lGv1PM5AwbMSkMwXvoM, but couldn't download http://x....x.noip.me/.well-known/acme-challenge/Eb0HflEdcibYcb-1lbR9QRa7lGv1PM5AwbMSkMwXvoM
```

**Comment by JANogueira** [comment]
I had the same problem. Ended up finding that my router didn't had the HTTP port opened. Only HTTPS. When opened port 80, all went just fine.
Seems to be the problem here as well according to your log.

**Comment by Yannik** [comment]
yeah, your server is just not reachable from the outside, which is a problem in your configuration.
