### ISSUE TITLE
Challenge did not pass

### ISSUE THREAD

**Issue by staypekos** [Yannik/qnap-letsencrypt#29]
**Platform/Firmware Information**
Platform = MARVELL_6281
Model = TS-212
Internal Model = TS-219
Version = 4.2.4
Build Number = 20170313
Rsync Model = QNAP
Build Date = 2017-03-13

**Is this the latest firmware for your device?**
Yes
**Issue Summary (provide relevant error messages and log output):**
{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:acme:error:connection",
    "detail": "Could not connect to myjablonec.sh.cvut.cz",
    "status": 400
  },
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/Otrz62phC-RVDFKiq08pGRwMDOA7ddec204kOOOnxpc/897859241",
  "token": "tkjr6EdFshw8V-xaov3N9KFSF_t0FxwK7QmTX9X1zd4",
  "keyAuthorization": "tkjr6EdFshw8V-xaov3N9KFSF_t0FxwK7QmTX9X1zd4.CmwEEFevk31s0HnYJBr_PA3TdSZI4LSSKA-JdAhvyk0",
  "validationRecord": [
    {
      "url": "http://myjablonec.sh.cvut.cz/.well-known/acme-challenge/tkjr6EdFshw8V-xaov3N9KFSF_t0FxwK7QmTX9X1zd4",
      "hostname": "myjablonec.sh.cvut.cz",
      "port": "80",
      "addressesResolved": [
        "147.32.119.192",
        "2001:718:2:91::64"
      ],
      "addressUsed": "147.32.119.192"
    }
  ]
}

**Comment by staypekos** [comment]
Tried with python server provided by renew script and also NAS Web server (using ports 80 and 443). Always the same error. Tried create dummy file and I'm able to get it with curl into NAS and via browser to my computer. I tried google a lot, but nothink helped. 
Thank you for your help

**Comment by Yannik** [comment]
well, the error message is pretty clear. your server is not reachable from the outside.

**Comment by staypekos** [comment]
Hi, thanks for response. As I wrote, I tried to download dummy file and it was possible from NAS with curl and via browser to my computer too.
Any advice  how to make my server reachable from outside? I have public IP.
Thank you

**Comment by Yannik** [comment]
You should try to reach your nas from a computer outside of your local network.

**Comment by Yannik** [comment]
On port 80.

**Comment by staypekos** [comment]
It is possilble. At least from all networks I tried. My server address is: http://myjablonec.sh.cvut.cz:80/.well-known/acme-challenge/
Can you reach it?

**Comment by Yannik** [comment]
I can reach it. I think lets encrypt should work too?

**Comment by Yannik** [comment]
I am not sure what is the problem in your case. You should try to debug this, maybe set up qnap-letsencrypt from a fresh clone, or use acme-tiny manually to assert what is causing this.

**Comment by Yannik** [comment]
I am not sure what is the problem in your case. You should try to debug this, maybe set up qnap-letsencrypt from a fresh clone, or use acme-tiny manually to assert what is causing this.

**Comment by staypekos** [comment]
I have new clone of the repository and I tried use renew script and acme-tiny manually (eith python server and with NAS web server) too.
I deleted all IP addresses from black list, the situation is still the same.
Thank you.

**Comment by Yannik** [comment]
You could try to use another acme client instead of acme-tiny.

**Comment by staypekos** [comment]
I just recieve firmware upgrade to version 4.3.3. In change-log is mention about support for Let's Encrypt. So I will see what can I do after upgrade.
Any recommendation for another acme client?

**Comment by staypekos** [comment]
When I tried it from NAS gui, I got message: "Authentication failed. Check DNS server or if port 80 works"

**Comment by Forsskieken** [comment]
Yes Let's Encrypt is now part of the Myqnapcloud and works when hosting a website.

**Comment by staypekos** [comment]
I comunicate wit QNAP support and they helped me with myqnapcloud Let's Encrypt certificate. Thank you for your time
