### ISSUE TITLE
signed.crt is missing while running renew_certificate.sh

### ISSUE THREAD

**Issue by christophergies** [Yannik/qnap-letsencrypt#3]
Hello,
I've got trouble while running ./renew_certificate.sh
there is no signed.crt in the path where the skript is looking for. Which of the previous steps should create it?

> 
[/share/MD0_DATA/git/LetsEncrypt/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Thu, 10 Mar 2016 23:06:07 +0100
Error opening Certificate ./letsencrypt/signed.crt
3070010544:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('./letsencrypt/signed.crt','r')
3070010544:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load certificate
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 11442
Could not import runpy module
Traceback (most recent call last):
  File "./acme-tiny/acme_tiny.py", line 2, in <module>
    import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
  File "/root/daily_build/4.2.0/Model/TS-419/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/argparse.py", line 85, in <module>
ImportError: No module named collections
--2016-03-10 23:06:16--  https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem
Resolving letsencrypt.org... 104.74.126.127, 2a02:26f0:cf:281::2a1f, 2a02:26f0:cf:285::2a1f
Connecting to letsencrypt.org|104.74.126.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1675 (1.6K) [application/x-x509-ca-cert]
Saving to: âSTDOUTâ

-                      100%[=============================>]   1.64K  --.-KB/s   in 0s

2016-03-10 23:06:16 (57.0 MB/s) - written to stdout [1675/1675]

Stopping stunnel and setting new stunnel certificates...
Shutting down apache proxy: OK
Done! Service startup and cleanup will follow now...
Start apache proxy: OK
./renew_certificate.sh: line 31: kill: (11442) - No such process
Starting Qthttpd services: Qthttpd.
[/share/MD0_DATA/git/LetsEncrypt/qnap-letsencrypt] # ls /etc/stunnel/ -l
-rw-------    1 admin    administ      1794 Aug  7  2015 backup.cert
-rw-------    1 admin    administ      1679 Aug  7  2015 backup.key
-rw-r--r--    1 admin    administ      1442 Aug 10  2015 stunnel.conf
-rw-r--r--    1 admin    administ      3350 Mar 10 23:06 stunnel.pem
-rw-r--r--    1 admin    administ      3350 Mar 10 22:11 stunnel.pem.letsencrypt
-rw-------    1 admin    administ      3467 Aug  7  2015 stunnel.pem.orig
-rw-------    1 admin    administ      3467 Aug  7  2015 stunnel.pem.temp
-rw-r--r--    1 admin    administ      1675 Mar 10 23:06 uca.pem
-rw-r--r--    1 admin    administ      1675 Mar 10 22:11 uca.pem.letsencrypt
>

**Comment by Yannik** [comment]
Hi @christophergies,
I have fixed the bug responsible for the error messages on lines 3-7 of your output.
signed.crt is generated by the first `renew_certificates.sh` run, on further runs it is checked for its expiry date. This was done (in error) even if the file didn't exist which lead to your problem.

Do you have any further issues? Please close this otherwise.

**Comment by christophergies** [comment]
Hey Yannik,

thank you for the quick response...
on my second run I get the following message and signed.crt is already empty :-(

> 
[/share/MD0_DATA/git/LetsEncrypt/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Thu, 10 Mar 2016 23:21:11 +0100
unable to load certificate
3069854896:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:696:Expecting: TRUSTED CERTIFICATE
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 12837
Could not import runpy module
Traceback (most recent call last):
  File "./acme-tiny/acme_tiny.py", line 2, in <module>
    import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
  File "/root/daily_build/4.2.0/Model/TS-419/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/argparse.py", line 85, in <module>
ImportError: No module named collections
--2016-03-10 23:21:20--  https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem
Resolving letsencrypt.org... 104.74.126.127, 2a02:26f0:cf:281::2a1f, 2a02:26f0:cf:285::2a1f
Connecting to letsencrypt.org|104.74.126.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1675 (1.6K) [application/x-x509-ca-cert]
Saving to: âSTDOUTâ

                      100%[=============================>]   1.64K  --.-KB/s   in 0s

2016-03-10 23:21:20 (53.7 MB/s) - written to stdout [1675/1675]

Stopping stunnel and setting new stunnel certificates...
Shutting down apache proxy: OK
Done! Service startup and cleanup will follow now...
Start apache proxy: OK
./renew_certificate.sh: line 31: kill: (12837) - No such process
Starting Qthttpd services: Qthttpd.

**Comment by Yannik** [comment]
This is the issue:
```
Traceback (most recent call last):
File "./acme-tiny/acme_tiny.py", line 2, in 
import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging
File "/root/daily_build/4.2.0/Model/TS-419/../../SysUtil/Python-2.7.5-cross/install_path_full/lib/python2.7/argparse.py", line 85, in 
ImportError: No module named collections
```
You need to make sure that your python installation contains the necessary modules. 
-- 
sent from mobile

Am 10. März 2016 23:39:51 MEZ, schrieb christophergies <notifications@github.com>:

**Comment by Yannik** [comment]
Specifically, you are missing the [collections](https://docs.python.org/2/library/collections.html) module which is required by the `argparse` module (which is necessary for acme-tiny).

**Comment by christophergies** [comment]
can you give me a short how-to how to install modules? I tried 

> 
python -m pip install collections

but I get always the message 

> Could not import runpy module

**Comment by christophergies** [comment]
when I use pip searching for a module named collection I get no result... :-( 
Any idea

**Comment by christophergies** [comment]
short update:
now I've uninstalled python 3.5 qkpg and installed python 2.7.3. qkpg, when I'm running renew_certificate.sh it's working. Also important: The Host must be reachable on Port 80!

**Comment by Yannik** [comment]
I have added a recommendation for python 2.7 (though it seems like a problem with your specific python 3.5 installation) and added a remark about being reachable on port 80.

Closing this now.
