### ISSUE TITLE
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge

### ISSUE THREAD

**Issue by qbox4u** [Yannik/qnap-letsencrypt#30]
several identical incidents are found on internet

File not found in any place
( expect that the flie was not written due to some ???)

Work around solution:

edit letsencrypt/qnap-letsencrypt/acme-tiny

disable the following lines

`#`        try:
`#`            resp = urlopen(wellknown_url)
`#`            resp_data = resp.read().decode('utf8').strip()
`#`            assert resp_data == keyauthorization
`#`        except (IOError, AssertionError):
`#`            os.remove(wellknown_path)
`#`            raise ValueError("Wrote file to {0}, but couldn't download {1}".format(
`#`               wellknown_path, wellknown_url))

**Comment by Yannik** [comment]
no.

**Comment by MartinHH** [comment]
Hint: QNAP recently deployed a lot of updates from QTS 4.2.x to QTS 4.3.3. After installing that update, I got the same error message when calling `.renew-cerificate.sh`. I found out that the reason for that was that my python installation was not active anymore. After restarting python (-> App-Center -> Python -> click on "Start"), everything went well.

**To put it short: if you get the above message, yo might want to check if python is available at all.**

**Comment by WilliamTheMarsman** [comment]
> no. removing those lines is not useful. the error just means that your server is not properly reachable.

My router does not support connecting to a local machine by DNS, so although the verification from an external network will pass, connecting internally using the DNS name will not. I had to remove those lines in order to get this to work.

Sure, the ideal would be fixing this at the router level, but that's not always possible.
