### ISSUE TITLE
Temporary Webserver does not stop if acme-tiny fails

### ISSUE THREAD

**Issue by andi98** [Yannik/qnap-letsencrypt#32]
Hi, we have a slow internet connection at our office, so sometimes the acme-tiny fails with `Could not connect to our.domain.tld`.
Thats not such a big problem, because I run the cronjob every night to make sure, that some day it works. The problem is, that the `renew_certificate.sh`-script crashes and does not start the normal web server again if acme-tiny fails. I need to kill the python-webserver and start the Qthttpd-service again by hand.
Maybe you can fix that in the `renew_certificate.sh`-script? Thanks for your work, saved me a lot of time!

**Platform/Firmware Information**

```
Platform = MARVELL_6281
Model = TS-421
Internal Model = TS-419
Version = 4.2.2
Build Number = 20161102
Rsync Model = QNAP
Build Date = 2016-11-02
```

**Comment by Yannik** [comment]
Feel free to submit a PR for this and I will review and merge it :)
