### ISSUE TITLE
needed to souce PATH /etc/profile.d/python2.bash

### ISSUE THREAD

**Issue by messimuc** [Yannik/qnap-letsencrypt#39]
**Platform/Firmware Information**
Platform = X86_CEDAVIEW
DISPLAY_NAME = TS-469L
Model = TS-469
Internal Model = TS-469
Version = 4.3.4
Build Number = 20171230
Rsync Model = QNAP
Build Date = 2017-12-30

**Is this the latest firmware for your device?**
yes

**Issue Summary (provide relevant error messages and log output):**
`/usr/local/bin/python: No module named SimpleHTTPServer`

after a`source /etc/profile.d/python2.bash` the SimpleHTTPServer started and everything worked.
got the idea from https://www.qnap.com/en/app_releasenotes/list.php?app_choose=Python

thanks for your work!

**Comment by Yannik** [comment]
Thanks for your report. 

Could you post the content of `/etc/profile.d/python2.bash` here please :)

**Comment by messimuc** [comment]
/etc/profile.d/python2.bash :
```
_PYTHON2_QPKG_BIN="/usr/local/python2/bin"
echo "${PATH}" | grep -q  ${_PYTHON2_QPKG_BIN} || export PATH=${_PYTHON2_QPKG_BIN}:${PATH}

```

**Comment by Yannik** [comment]
Interesting. What is the output of

ls -alsh /usr/local/python2/bin/
and
ls - alsh /etc/profile.d/python2.bash

**Comment by messimuc** [comment]
ls -alsh /usr/local/python2/bin/ :
```
4.0K drwxr-xr-x 2 admin           1000 4.0K 2016-08-10 12:37 ./
4.0K drwxr-xr-x 6 admin administrators 4.0K 2017-10-17 11:14 ../
4.0K -rwxr-xr-x 1 admin           1000  109 2016-08-10 11:17 2to3*
4.0K -rwxr-xr-x 1 admin           1000  107 2016-08-10 11:17 idle*
4.0K -rwxr-xr-x 1 admin           1000   92 2016-08-10 11:17 pydoc*
   0 lrwxrwxrwx 1  1000           1000    7 2017-12-02 13:27 python -> python2*
   0 lrwxrwxrwx 1  1000           1000    9 2017-12-02 13:27 python2 -> python2.7*
7.4M -rwxrwxrwx 1 admin           1000 7.4M 2016-08-10 12:37 python2.7*
4.0K -rwxrwxrwx 1 admin           1000 1.7K 2016-08-10 12:37 python2.7-config*
   0 lrwxrwxrwx 1  1000           1000   16 2017-12-02 13:27 python2-config -> python2.7-config*
   0 lrwxrwxrwx 1  1000           1000   14 2017-12-02 13:27 python-config -> python2-config*
 20K -rwxr-xr-x 1 admin           1000  19K 2016-08-10 11:17 smtpd.py*
```
ls -alsh /etc/profile.d/python2.bash  (removed the space between - and alsh) :
`0 lrwxrwxrwx 1 admin administrators 41 2018-01-06 13:50 /etc/profile.d/python2.bash -> /share/MD0_DATA/.qpkg/Python/python2.bash`

**Comment by Yannik** [comment]
That's rather interesting. Did you install the python qpkg recently or in 2016?

**Comment by Yannik** [comment]
I'd additionally be interested in the output of the following commands on your system:

```
find / -name python
time find /share/ -mindepth 1 -maxdepth 2 -type d -name .qpkg
time find /share/ -type d -path /share/*/.qpkg/Python/bin
```

**Comment by messimuc** [comment]
hi yannik, I canceled the "deep" find_s after one hour - the qnap is a rsync destination with >10 million files
find / -name python :
```
/usr/local/bin/python
/share/MD0_DATA/.qpkg/Qffmpeg/bin/python
/share/MD0_DATA/.qpkg/Qffmpeg/include/boost/mpi/python
/share/MD0_DATA/.qpkg/Qffmpeg/include/boost/parameter/aux_/python
/share/MD0_DATA/.qpkg/Qffmpeg/include/boost/python
/share/MD0_DATA/.qpkg/Qffmpeg/lib/graphviz/python
/share/MD0_DATA/.qpkg/CloudDriveSync/python
/share/MD0_DATA/.qpkg/CloudDriveSync/python/bin/python
/share/MD0_DATA/.qpkg/CloudDrive/python
/share/MD0_DATA/.qpkg/CloudDrive/python/bin/python
/share/MD0_DATA/.qpkg/CloudDrive/clouddrive/python
/share/MD0_DATA/.qpkg/Python/bin/python
/share/MD0_DATA/.qpkg/Python/src/bin/python
> 1h - canceled
```
time find /share/ -mindepth 1 -maxdepth 2 -type d -name .qpkg :
```
/share/MD0_DATA/.qpkg

real	0m1.017s
user	0m0.011s
sys	0m0.020s
```
time find /share/ -type d -path /share/*/.qpkg/Python/bin
```
/share/MD0_DATA/.qpkg/Python/bin
> 1h - canceled
```
/usr/local/python2/bin/python --version
`Python 2.7.5`
which python
`/usr/local/bin/python`

after source /etc/profile.d/python2.bash
/usr/local/python2/bin/python --version
`Python 2.7.12`
which python
`/usr/local/python2/bin/python`

 I will be offline for a week

**Comment by Yannik** [comment]
Hey, there's two questions you skipped ;)

> Did you install the python qpkg recently or in 2016?

> what is the output of `realpath $(which python)` after doing `source ...`?

**Comment by Yannik** [comment]
Should be fixed with latest commits.
