### ISSUE TITLE
No module named SimpleHTTPServer

### ISSUE THREAD

**Issue by L0g333** [Yannik/qnap-letsencrypt#40]
**Platform/Firmware Information**

Run
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-451+
```

grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
```
Model = TS-X51
Internal Model = TS-X51
Version = 4.3.4
Build Number = 20171230
Rsync Model = QNAP
Build Date = 2017-12-30
```

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**

Hi,

I've been running qnap-letsencrypt for almost a year now without any problems. Sadly since the most recent Firmware Upgrade (QTS 4.3.3 -> 4.3.4) my certificates don't get renewed anymore. So i first replaced the renew_certificate.sh file by the one which was uploaded 20 days ago to github.

Sadly the renew_certificate.sh still crashes with the same error (see below). Obviously in line 4 the simpleHTTPserver can't be found/loaded. The line below sais that the python2 file cannot be found. I already checked whether python 2.7 is installed. It is. I also reinstalled it. No change. I tried removing Pyhton 2.7 and installing python 3.5. Still the same result. 

Hope you can help me, with this issue. :) 

By now, thank you for this really helpful script. It's much better then the qnap implementation of lets encrypt :)

```
Checking whether to renew certificate on Sun, 28 Jan 2018 20:51:22 +0100
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named SimpleHTTPServer
./renew_certificate.sh: line 10: /share/CE_CACHEDEV1_DATA/.qpkg/Python/bin/python2: No such file or directory
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 20622
/share/CE_CACHEDEV1_DATA/.qpkg/Python/src/bin/python2: can't open file '../HTTPServer.py': [Errno 2] No such file or directory
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying my.domain.here...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/va6qjn6idPB3CJzlGwJxf5xusn0oFQ9ws8d7CL-M2qA, but couldn't download http://my.domain.here/.well-known/acme-challenge/va6qjn6idPB3CJzlGwJxf5xusn0oFQ9ws8d7CL-M2qA
```

**Comment by Yannik** [comment]
Hi,

what is the output of

```
if python -c "import SimpleHTTPServer"; then
    PYTHON=python
elif "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"; then
    PYTHON="$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2"
elif "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2" -c "import SimpleHTTPServer"; then
    PYTHON="$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2"
elif /sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf; then
    PYTHON="$(/sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf)/python3/bin/python3"
fi
echo $PYTHON
```

**Comment by L0g333** [comment]
Wow. That was quick!

Ehm. I am not sure if I did it the correct way: I pasted your code to a file named "test.sh" in the qnap-letsencrypt directory and gave it executable permissions and executed it via CLI. Output is:

```
[/share/homes/admin/qnap-letsencrypt] # ./test.sh
./test.sh: line 3: syntax error near unexpected token `elif'
'/test.sh: line 3: `elif "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"; then
```

**Comment by Yannik** [comment]
Not sure what went wrong there. 
Just try these simple commands from the commandline and post the output of each:
```
python -c "import SimpleHTTPServer"
"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"
"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2" -c "import SimpleHTTPServer"
/sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf
```

**Comment by L0g333** [comment]
Here is the output. Just pasted everything line by line:

```
[/share/homes/admin/qnap-letsencrypt] # python -c "import SimpleHTTPServer"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named SimpleHTTPServer
[/share/homes/admin/qnap-letsencrypt] # "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"
-sh: /share/CE_CACHEDEV1_DATA/.qpkg/Python/bin/python2: No such file or directory
[/share/homes/admin/qnap-letsencrypt] # "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2" -c "import SimpleHTTPServer"
[/share/homes/admin/qnap-letsencrypt] # /sbin/getcfg Python3 Install_Path -f /etc/config/qpkg.conf
[/share/homes/admin/qnap-letsencrypt] #

```

**Comment by Yannik** [comment]
If you manually start python using `"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2"`, can you import the http server module?

**Comment by L0g333** [comment]
Looks good.

```
[/share/homes/admin/qnap-letsencrypt] # "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2"
Python 2.7.12 (default, Aug 10 2016, 17:16:35)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimpleHTTPServer
>>> exit()
```

**Comment by Yannik** [comment]
Are you sure that you updated the renew script in the right place? The latest version should autodetect the python installation we just tested... (I published another update a few minutes ago, so feel free to test that one)

**Comment by L0g333** [comment]
100%. Just downloaded the new file, renamed the old one, placed the new one in the directory and gave it the execution permissions. Heres the stats (see the timestamp :P ) and the execution output:

```
[/share/homes/admin/qnap-letsencrypt] # stat ./renew_certificate.sh
  File: ./renew_certificate.sh
  Size: 2132            Blocks: 8          IO Block: 4096   regular file
Device: fc24h/64548d    Inode: 82347666    Links: 1
Access: (0760/-rwxrw----)  Uid: (    0/   admin)   Gid: (    0/administrators)
Access: 2018-01-28 21:24:45.000000000
Modify: 2018-01-28 21:19:51.000000000
Change: 2018-01-28 21:24:43.000000000

[/share/homes/admin/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sun, 28 Jan 2018 21:25:52 +0100
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named SimpleHTTPServer
./renew_certificate.sh: line 10: /share/CE_CACHEDEV1_DATA/.qpkg/Python/bin/python2: No such file or directory
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 16406
/share/CE_CACHEDEV1_DATA/.qpkg/Python/src/bin/python2: can't open file '../HTTPServer.py': [Errno 2] No such file or directory
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying my.domain.here...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/va6qjn6idPB3CJzlGwJxf5xusn0oFQ9ws8d7CL-M2qA, but couldn't download http://my.domain.here/.well-known/acme-challenge/va6qjn6idPB3CJzlGwJxf5xusn0oFQ9ws8d7CL-M2qA
[/share/homes/admin/qnap-letsencrypt] #
```

**Comment by Yannik** [comment]
What is the output of `"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"; echo $?`?

**Comment by L0g333** [comment]
```
[/share/homes/admin/qnap-letsencrypt] # "$(/sbin/getcfg Python Install_Path -f [/share/homes/admin/qnap-letsencrypt] # "$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer"; echo $?
-sh: /share/CE_CACHEDEV1_DATA/.qpkg/Python/bin/python2: No such file or directory
127
[/share/homes/admin/qnap-letsencrypt] #
[/share/homes/admin/qnap-letsencrypt] # cd /share/CE_CACHEDEV1_DATA/
[/share/CE_CACHEDEV1_DATA] # ls
aquota.user  Container/  Download/  homes/  lost+found/  mediasoulutions/  Multimedia/  Public/  _.share/  VM/  Web/

```

in CE_CACHEDEV1_DATA there really is no .qpgk folder. Is it possible that with QTS 4.3.4 something changed here?

**Comment by Yannik** [comment]
Try 

"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer" && echo success || echo failed
"$(/sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf)/src/bin/python2" -c "import SimpleHTTPServer" && echo success || echo failed

**Comment by L0g333** [comment]
```
<Install_Path -f /etc/config/qpkg.conf)/bin/python2" -c "import SimpleHTTPServer" && echo success || echo failed
-sh: /share/CE_CACHEDEV1_DATA/.qpkg/Python/bin/python2: No such file or directory
failed
<Install_Path -f /etc/config/qpkg.conf)/src/bin/python2" -c "import SimpleHTTPServer" && echo success || echo failed
success
[/share/CE_CACHEDEV1_DATA] #

```

**Comment by Yannik** [comment]
Okay, first, you should try the latest version and list its output here. 
Second, your issue is this:
`/share/CE_CACHEDEV1_DATA/.qpkg/Python/src/bin/python2: can't open file '../HTTPServer.py': [Errno 2] No such file or directory`

The HTTPServer.py binary is missing. I believe that is due to you not updating the qnap-letsencrypt repo. You should always use `git pull` to update.

**Comment by L0g333** [comment]
Yap. Seems to work now.

```
[/share/homes/admin/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sun, 28 Jan 2018 21:54:48 +0100
[/share/homes/admin/qnap-letsencrypt] #
```


Thank you for the quick and extensive help!

**Comment by Yannik** [comment]
You're welcome.

**Comment by L0g333** [comment]
Is there an option to donate the project? ;)

BTW: Gerade gesehen, dass du ja auch aus Deutschland bist ;)

**Comment by Yannik** [comment]
Feel free to send a few bucks this way: https://www.paypal.me/qnapletsencrypt

Tatsächlich habe ich selber schon länger kein Qnap Nas mehr, daher freut es mich um so mehr, ein wenig Anerkennung für die weitere Pflege dieses Projekts zu erhalten ;-)

**Comment by L0g333** [comment]
Ach krass. Bist du auf was anderes umgestiegen, oder hast du gar kein NAS mehr?

Solltest jetzt etwas mehr paypal Guthaben haben ;)

**Comment by Yannik** [comment]
Lieben Dank :-)
Zumindest kein fertiges NAS von QNAP/Synology und Konsorten mehr. Stattdessen ein HP Microserver (ein N54L, hat damals glaub ich 150€ gekostet) mit Debian. Administrieren tue ich das ganze über Ansible (siehe auch meine ganze anderen github projekte ;-)). So ein fertiges NAS bringt häufig ganz viel mit, was man nicht braucht. Und das was man braucht, fehlt dann, ist schwierig zu konfigurieren oder ist nicht flexibel genug ;-)
Ich persönlich könnte mir nicht vorstellen, zu den Einschränkungen und Herstellerabhängigkeiten eines fertigen NAS zurückzugehen. Das muss aber jeder selbst entscheiden, denn man muss schon etwas an Linux-Kenntnissen erwerben um so eine Kiste selbst administrieren zu können.

**Comment by L0g333** [comment]
Hat alles so seine Vor- und Nachteile. Prinzipiell finde ich eine selbst zusammengebaute und administrierte Kiste auch deutlich besser. Allerdings bietet mir QNAP zur Zeit den Vorteil, dass das Teil einfach läuft und ich mich (eigtl.) um fast nix kümmern muss. Neben Studium und Selbstständigkeit fehlt mir aktuell einfach die Zeit mich mit der Materie auseinanderzusetzen und mir den Server so zusammenzubauen wie ich ihn bräuchte.

Hab allerdings parallel auch noch einen Server rumstehen (HP ML10v2). Da läuft meine ESXi mit Starface TK-Anlage, Sophos Firewall und diverser Testsysteme drauf. Vllt. folgt irgendwann noch ein NAS Marke Eigenbau :D
