### ISSUE TITLE
Feature request: Wildcard Certificates

### ISSUE THREAD

**Issue by trond7** [Yannik/qnap-letsencrypt#43]
#As of february 2018, letsencrypt.org will support Wildcard Certificates.
See: https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

It would be fantastic if your script would support that.

**Comment by Yannik** [comment]
According to the blog post you linked, wildcard certificates will only be available through DNS validation, which is not what this script does. So unfortunately, it won't be possible to support this unless other methods of validation are supported for wildcard certificates. (Also, DNS validation is highly dependant on your DNS hoster/server, so it will ultimately be impossible to support more than a few hosters in a single script)
