### ISSUE TITLE
Verification fails

### ISSUE THREAD

**Issue by aski71** [Yannik/qnap-letsencrypt#45]
**Platform/Firmware Information**
QNAP TS-459 / Firmware 4.2.6

Platform = X86_PINEVIEW
Model = TS-459
Internal Model = TS-459
Version = 4.2.6
Build Number = 20171208
Rsync Model = QNAP
Build Date = 2017-12-08

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
`Checking whether to renew certificate on Fri, 13 Apr 2018 13:08:00 +0200
Renewing certificate...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying big....my.cloud.com...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 111, in get_crt
    with open(wellknown_path, "w") as wellknown_file:
IOError: [Errno 2] No such file or directory: u'/share/MD0_DATA/Web/.well-known/acme-challenge/8k0LtdszusdOOWkJGoqTozUOJse2gGsNmYLYc4rgOk8'`

There already is a closed thread here with the same issue.
The solution was: Port 80 was not open. The machine was not reachable from the internet.
This is not the case here!
Port 80 is open and the machine is reachable from the internet.

Please help.
Thanks, Alex

**Comment by Yannik** [comment]
i think you could try to execute the script from the qnap-letsencrypt directory. there obviously is a problem with creating the challenge file on your local machine.

**Comment by aski71** [comment]
I already did that with the same result.
Why did you immediately close this issue?
