### ISSUE TITLE
Still certificate update issue

### ISSUE THREAD

**Issue by aski71** [Yannik/qnap-letsencrypt#46]
Yannik,
I still have this problem and don't know how to solve it.
I did what you proposed even before you proposed it. And the output below is the output by calling it from the directory it's installed in.
Thank you for your help.

Best regards, Alex 

----

Platform/Firmware Information
QNAP TS-459 / Firmware 4.2.6

Platform = X86_PINEVIEW
Model = TS-459
Internal Model = TS-459
Version = 4.2.6
Build Number = 20171208
Rsync Model = QNAP
Build Date = 2017-12-08

Is this the latest firmware for your device?
Yes

Issue Summary (provide relevant error messages and log output):
Checking whether to renew certificate on Fri, 13 Apr 2018 13:08:00 +0200 Renewing certificate... Parsing account key... Parsing CSR... Registering account... Already registered! Verifying big....my.cloud.com... Traceback (most recent call last): File "acme-tiny/acme_tiny.py", line 198, in <module> main(sys.argv[1:]) File "acme-tiny/acme_tiny.py", line 194, in main signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca) File "acme-tiny/acme_tiny.py", line 111, in get_crt with open(wellknown_path, "w") as wellknown_file: IOError: [Errno 2] No such file or directory: u'/share/MD0_DATA/Web/.well-known/acme-challenge/8k0LtdszusdOOWkJGoqTozUOJse2gGsNmYLYc4rgOk8'

There already is a closed thread here with the same issue.
The solution was: Port 80 was not open. The machine was not reachable from the internet.
This is not the case here!
Port 80 is open and the machine is reachable from the internet.

Please help.
Thanks, Alex

**Comment by Yannik** [comment]
I'm happy to take pull requests, but as it is, I have no way of knowing what causes this issue. Did you get it fixed in the meantime?

**Comment by aski71** [comment]
No. I did not, unfortunately.
How can I diagnose this any further?

**Comment by aski71** [comment]
Hi Yannik,
found it out and fixed it.
Turns out it was my fault all along.
When I implemented this initially, I deleted the part where you kill the web server and start your own.
Instead I change the command to use the official web-root of the QNAP (/share/MD0_DATA/Web).
What I didn't notice was that the script in the end deletes the .well-known/acme-challenge directory again.
As I didn't create it in the script, the challenge file could not be placed and the operation failed.
So I changed the script now to create the two directories again.
Seems to be fine now.

Thanks and sorry!
Alex

`set -e

# do nothing if certificate is valid for more than 30 days (30*24*60*60)
echo "Checking whether to renew certificate on $(date -R)"
[ -s letsencrypt/signed.crt ] && openssl x509 -noout -in letsencrypt/signed.crt -checkend 2592000 && exit

echo "Renewing certificate..."
cd /share/MD0_DATA/letsencrypt/qnap-letsencrypt
export SSL_CERT_FILE=cacert.pem
mkdir -p /share/MD0_DATA/Web/.well-known/acme-challenge

python acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir /share/MD0_DATA/Web/.well-known/acme-challenge > letsencrypt/signed.crt
echo "Downloading intermediate certificate..."
wget --no-verbose -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem
cat letsencrypt/signed.crt letsencrypt/intermediate.pem > letsencrypt/chained.pem

echo "Stopping stunnel and setting new stunnel certificates..."
/etc/init.d/stunnel.sh stop
cat letsencrypt/keys/domain.key letsencrypt/chained.pem > /etc/stunnel/stunnel.pem
cp letsencrypt/intermediate.pem /etc/stunnel/uca.pem

echo "Done! Service startup and cleanup will follow now..."
/etc/init.d/stunnel.sh start

rm -rf /share/MD0_DATA/Web/.well-known`

**Comment by Yannik** [comment]
Glad that you found the issue :)
