### ISSUE TITLE
ValueError - ordinal not in range(128)

### ISSUE THREAD

**Issue by luckylefti** [Yannik/qnap-letsencrypt#49]
**Platform/Firmware Information**

```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-251
Model = TS-X51
Internal Model = TS-X51
Version = 4.3.4
Build Number = 20180528
Rsync Model = QNAP
Build Date = 2018-05-28
```

**Is this the latest firmware for your device?**
Yes: 4.3.4.0597

**Issue Summary (provide relevant error messages and log output):**
After running renew_certificate.sh i got following error:

Parsing account key...
Parsing CSR...
Found domains: XXX.XX
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying XXX.XX...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 144, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/jz8O3fDnsaEdQVASS9brcBDWM2Hv04Qg-ayar26IRmE, but couldn't download http://XXX.XX/.well-known/acme-challenge/jz8O3fDnsaEdQVASS9brcBDWM2Hv04Qg-ayar26IRmE: 'ascii' codec can't encode characters in position 2602-2603: ordinal not in range(128)

Any ideas

**Comment by Yannik** [comment]
Does this happen repeatedly?

**Comment by luckylefti** [comment]
Yes, always

**Comment by Yannik** [comment]
Maybe non-ascii characters in your domain name?

**Comment by Yannik** [comment]
Close due to inactivity
