### ISSUE TITLE
Certificat isn't working 

### ISSUE THREAD

**Issue by christophergies** [Yannik/qnap-letsencrypt#5]
**Platform/Firmware Information**

```
Platform = MARVELL_6281
Model = TS-419P
Internal Model = TS-419
Version = 4.2.0
Build Number = 20160311
Rsync Model = QNAP
Build Date = 2016-03-11
```

Hello Yannik,

When I'm running renew_certificate.sh I get following output:

```
Checking whether to renew certificate on Wed, 30 Mar 2016 23:00:00 +0200
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python SimpleHTTPServer with pid 28775
Serving HTTP on 0.0.0.0 port 80 ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying XXX.myqnapcloud.com...
ip-176-198-9-237.hsi05.unitymediagroup.de - - [30/Mar/2016 23:00:31] "GET /.well-known/acme-challenge/ixw4XfkLptjvWfQpcFagsJWaVUEBcGO7oJVif-yMIZw HTTP/1.1" 200 -
outbound1.letsencrypt.org - - [30/Mar/2016 23:00:34] "GET /.well-known/acme-challenge/ixw4XfkLptjvWfQpcFagsJWaVUEBcGO7oJVif-yMIZw HTTP/1.1" 200 -
cgies.myqnapcloud.com verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
2016-03-30 23:00:38 URL:https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem [1675/1675] -> "-" [1]
Stopping stunnel and setting new stunnel certificates...
Shutting down apache proxy: OK
Done! Service startup and cleanup will follow now...
Start apache proxy: OK
df: /share/external/Etron xHCI Host Controller: Protocol error
Starting Qthttpd services: Qthttpd.
```

When I'm accessing the Server via https Firefox says: SEC_ERROR_UNKNOWN_ISSUER

Any idea?

**Comment by Yannik** [comment]
Please post the output of https://www.ssllabs.com/ssltest/analyze.html here.

**Comment by christophergies** [comment]
Maybe its more easy to check it yourself then post the output here. My Hostname is cgies.myqnapcloud.com

Chrome has no problem and says everything is fine!

**Comment by Yannik** [comment]
```
Common names 	pon4xgnvk2sjulgv.myfritz.net   MISMATCH
Alternative names 	pon4xgnvk2sjulgv.myfritz.net fritz.box www.fritz.box myfritz.box www.myfritz.box fritz.nas www.fritz.nas
```
definitely not the certificate generated by the script that you are serving here, for me it doesn't work in chrome either. (Certificate mismatch).

**Comment by christophergies** [comment]
hmmm I think this is the certificate from my router... but what can I do? I dont understand...

**Comment by Yannik** [comment]
well you probably need to setup port forwarding from your router to your nas.

**Comment by christophergies** [comment]
I've setup port forwarding from router to nas on port 450 is this the reason? Is it only working on 433?

**Comment by Yannik** [comment]
you need to forward port 443 or the ssl labs check will not work. i am pretty sure your issue is the intermediate certificate but we will need the ssl labs results.

**Comment by christophergies** [comment]
ok I will check this, moment pleas

**Comment by christophergies** [comment]
sorry I've to check this tomorrow. Now I've changed the ssl port of the Router for remote access but I cant connect... :-(

**Comment by christophergies** [comment]
Hey Yannik, 
I'm sorry for my late response, but I'm really busy this days! Now I've changed my port forwarding so that the System is reachable via Port 443. The ssl labs results says, that the certification chain is incomplete. Maybe you can start the test on yourselfe and see if you have any ideas how to fix this problem. Hostname: cgies.myqnapcloud.com
Thank you very much!

**Comment by jorhett** [comment]
LGTM

![screen shot 2016-04-08 at 10 31 30 am](https://cloud.githubusercontent.com/assets/1417194/14392227/30078a48-fd75-11e5-9f75-790e15e36793.png)

**Comment by Yannik** [comment]
Have you tried the latest version of qnap-letsencrypt? There was a change regarding the intermediate cert in the last commit.

**Comment by Yannik** [comment]
Yes, I have just checked your installation and the error you are experiencing is fixed in the latest version of qnap-letsencrypt already.

**Comment by christophergies** [comment]
Now it's working! Thanks!
