### ISSUE TITLE
Challenge did not pass

### ISSUE THREAD

**Issue by suprawsmninja** [Yannik/qnap-letsencrypt#50]
after running renew_certificate.sh  I get this:

Checking whether to renew certificate on Sat, 07 Jul 2018 16:36:20 +0800
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 5121
Parsing account key...
Parsing CSR...
Found domains: xxxx.dyndns.org
Getting directory...
00.00.00.00 - - [07/Jul/2018 16:36:31] "GET / HTTP/1.1" 200 -
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying xxxx.dyndns.org...
00.00.00.00 - - [07/Jul/2018 16:36:45] "GET /.well-known/acme-challenge/kT8yQ6jhjkxBtbp0IExvCkgF_b2YQSsWW1AcUboMM4c HTTP/1.1" 200 -
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 150, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for xxxx.dyndns.org: {'challenges': [{'token': 'kT8yQ6jhjkxBtbp0IExvCkgF_b2YQSsWW1AcUboMM4c', 'validationRecord': [{'addressUsed': '00.00.00.00', 'addressesResolved': ['00.00.00.00'], 'port': '80', 'url': 'http://xxxx.dyndns.org/.well-known/acme-challenge/kT8yQ6jhjkxBtbp0IExvCkgF_b2YQSsWW1AcUboMM4c', 'hostname': 'xxxxdyndns.org'}], 'error': {'type': 'urn:ietf:params:acme:error:connection', 'detail': 'Fetching http://xxxx.dyndns.org/.well-known/acme-challenge/kT8yQ6jhjkxBtbp0IExvCkgF_b2YQSsWW1AcUboMM4c: Timeout during connect (likely firewall problem)', 'status': 400}, 'status': 'invalid', 'type': 'http-01', 'url': 'https://acme-v02.api.letsencrypt.org/acme/challenge/3JG7Hsqy5506bGRS4iosxFMV3uZDF6q67zI421Fn7Pc/5515119562'}, {'token': 'Fn4VzJ3ELa6JsHM_taf0XFWd5Y6cg_WR75Zd9C2y3JQ', 'type': 'dns-01', 'url': 'https://acme-v02.api.letsencrypt.org/acme/challenge/3JG7Hsqy5506bGRS4iosxFMV3uZDF6q67zI421Fn7Pc/5515119563', 'status': 'invalid'}], 'expires': '2018-07-14T08:36:34Z', 'identifier': {'type': 'dns', 'value': 'xxxx.dyndns.org'}, 'status': 'invalid'}

The sever is accessable for the though?
\# 00.00.00.00 - - [07/Jul/2018 17:43:44] "GET /.well-known/acme-challenge/ HTTP/1.1" 200 -

**Comment by Yannik** [comment]
Seems like something you'll have to fix on your side.

**Comment by suprawsmninja** [comment]
Ok fixed that issue - port was blocked at my ISP.

Now getting issue with wget

wget --no-verbose -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem

wget: unrecognized option '--no-verbose'

tried:
wget --no-check-certificate -O https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem letsencrypt/intermediate.pem

wget: unrecognized option '--no-check-certificate'

Either way fails and Qnap wget doesn't support SSL? How di you and others overcome this?
I'm no rate limited by letsencrypt so will need to try again next week.
