### ISSUE TITLE
renew_certificate.sh error

### ISSUE THREAD

**Issue by ash73** [Yannik/qnap-letsencrypt#52]
I installed qnap-letsencrypt on a TS-121, and it gives the following error.

The part-finished script has also disabled the web server and its port 80 subscription, and I don't know how to re-enable it. I fixed it once already with a factory reset but don't want to do that again!

I've been trying to sort this all day, any help would be appreciated.

(I've changed my actual domain name in the log to MYADDRESS).

Platform = MARVELL_6281

Model = TS-121
Internal Model = TS-119
Version = 4.3.3
Build Number = 20180725
Rsync Model = QNAP
Build Date = 2018-07-25

Checking whether to renew certificate on Mon, 30 Jul 2018 19:15:21 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 3147
Parsing account key...
Parsing CSR...
Found domains: MYADDRESS
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying MYADDRESS...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 141, in get_crt
    assert(disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://MYADDRESS/.well-known/acme-challenge/XunRG8JKKJEmCT0Bu_-jct-JD37xUB_CRJR5jtwwkow
Data: None
Response Code: None
Response: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 144, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/XunRG8JKKJEmCT0Bu_-jct-JD37xUB_CRJR5jtwwkow, but couldn't download http://MYADDRESS/.well-known/acme-challenge/XunRG8JKKJEmCT0Bu_-jct-JD37xUB_CRJR5jtwwkow: Error:
Url: http://MYADDRESS/.well-known/acme-challenge/XunRG8JKKJEmCT0Bu_-jct-JD37xUB_CRJR5jtwwkow
Data: None
Response Code: None
Response: <urlopen error [Errno 110] Connection timed out>

**Comment by ash73** [comment]
For anyone else encountering this issue, to at least get your basic http web server working again after this script fails:

ps -ef | grep python

  700 admin       752 S   grep python
xxxxx admin      9340 S   /share/HDA_DATA/.qpkg/Python3/python3/bin/python3 ../HTTPServer.py

kill -9 xxxxx
/etc/init.d/Qthttpd.sh start

**Comment by Yannik** [comment]
It seems like the connection to MYADDRESS does not work.

**Comment by ash73** [comment]
It looks that way but MYADDRESS does work ok, I can view a http web page remotely, I can connect to the NAS VPN server using that address etc. The router forwards ports 80, 8081 and 443 (amongst others) to the NAS, I'm not sure what else to check.

**Comment by ash73** [comment]
@Yannik I see closed issue #32 described the same problem, it would have saved me a lot of time. Can I suggest you at least put a note on the homepage to say:

1. If the script fails you must manually kill the HTTPServer.py process and restart Qthttpd.sh
2. If that doesn't work you must do a factory reset (hold the reset button for 10 secs), so backup your NAS settings and apache.config first

**Comment by Yannik** [comment]
@ash73 well, feel free to submit a PR for a recovery routine. 
IMO most people familiar with linux will associate their webservice being down with "hmm, I'll need to start it again - Oh, Qthttpd.sh, it's right in the script. Fails due to ports being taken? check what's hogging them - oh, python". 
there are definitely no reasons to do a factory reset at all.

about your initial report: I have a theory that your issue has to do with your router not routing your public ip back in. can you reach MYADDRESS from your internal network?

**Comment by ash73** [comment]
I have two QNAPs in two sites, both the same model, one works fine the other refuses to play ball, it's a mystery. If I find time I might modify the script to stop it creating a new web server and borking the existing one, no idea why it needs to do that.

To be honest even if I got it working I've seen enough to know the script is not robust enough to put in crontab, it doesn't fail gracefully. I'll remove it and find another solution, thanks anyhow.
