### ISSUE TITLE
ValueError: Error registering: 400 "type": "urn:acme:error:malformed"

### ISSUE THREAD

**Issue by OeveringIT** [Yannik/qnap-letsencrypt#53]
**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-659
Internal Model = TS-659
Version = 4.2.6
Build Number = 20180711
Rsync Model = QNAP
Build Date = 2018-07-11

```

**Is this the latest firmware for your device?**
Yes it is

**Issue Summary (provide relevant error messages and log output):**
Hi, I've been using this for a while now and really enjoy it!

However it seems to have stoped working (had the cronjob running and everything).
So I did a update of the files with "git fetch origin". 

Now when I check the log I first off always see an error that port 80 is already in use (witch it iss'nt).
Also I get een error that the provided URL does not match current agreement. Already ran init.sh again and following your guide steps 'Setting up qnap-letsencrypt'.

How to fix?

```Checking whether to renew certificate on Thu, 09 Aug 2018 11:49:38 +0200
Renewing certificate...
Stopping Qthttpd hogging port 80.. and kill previous Python HTTPserver
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 29273
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/lib/python2.7/threading.py", line 754, in run
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/opt/lib/python2.7/SocketServer.py", line 417, in __init__
  File "/opt/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
  File "/opt/lib/python2.7/SocketServer.py", line 431, in server_bind
  File "/opt/lib/python2.7/socket.py", line 228, in meth
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme-tiny/acme_tiny.py", line 92, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]"
  "status": 400
}
```

**Comment by Yannik** [comment]
update acme-tiny.

**Comment by OeveringIT** [comment]
Thanks for that and for the quick anwser! Maby you can take it up in your scripts of readme somewhere? I forgot it is a repo as well.

Stil it's not fully fixed, now I get "Connection Time-out" Nothing in the infrastructure changed, port forwards are still vailid and working (tested internaly and externaly) but no incomming connection from Let's Encrypt to the python HTTP server (I checked the renew_certificate.log).

Could the connection be using tls-alpn-01? I want to check the connection log of QTS but could'nt find it.

https://letsdebug.net/ with http-01 gives an "ALL OK".

Any thougts?

**Comment by Yannik** [comment]
hey @OeveringIT, is this still an issue for you?

**Comment by OeveringIT** [comment]
Hey @Yannik ya it is, at the moment i'm not able to renew the ssl certificate via your tool :(.

Anything I can do to help you with finding the root cause?

**Comment by Yannik** [comment]
@OeveringIT Can you please remove qnap-letsencrypt completely, set it up again, and then post the complete error output.

**Comment by boevering** [comment]
Hey @Yannik I've got it to work, still some error's though but I've put in some handwork.

What I got now is:
`[/share/MD0_DATA/Lets/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sat, 26 Jan 2019 15:53:46 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 32713
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/lib/python2.7/threading.py", line 754, in run
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/opt/lib/python2.7/SocketServer.py", line 418, in __init__
  File "/opt/lib/python2.7/SocketServer.py", line 440, in server_activate
  File "/opt/lib/python2.7/socket.py", line 228, in meth
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Found domains: qnap.domain.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying qnap.domain.com...
::ffff:10.x.x.x - - [26/Jan/2019 15:53:56] "GET /.well-known/acme-challenge/0YFlo0oZlWlCAi<<<<<>>>>>>>>YKjrYiw8kf-LamM HTTP/1.1" 200 -
::xxx:xxx:xx:xxx - - [26/Jan/2019 15:53:58] "GET /.well-known/acme-challenge/0YFlo0oZlWlCAi<<<<<>>>>>>>>YKjrYiw8kf-LamM HTTP/1.1" 200 -
qnap.domain.com verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
wget: unrecognized option '--no-verbose'
BusyBox v1.27.2 () multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
        [--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
        [-S|--server-response] [-U|--user-agent AGENT] URL...

Retrieve files via HTTP or FTP

        --spider        Only check URL existence: $? is 0 if exists
        -c              Continue retrieval of aborted transfer
        -q              Quiet
        -P DIR          Save to DIR (default .)
        -S              Show server response
        -O FILE         Save to FILE ('-' for stdout)
        -U STR          Use STR for User-Agent header
        -Y on/off       Use proxy
`

**Comment by OeveringIT** [comment]
Hey @Yannik I've got it to work, still some error's though but I've put in some handwork.

What I got now is:
`[/share/MD0_DATA/Lets/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sat, 26 Jan 2019 15:53:46 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 32713
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/opt/lib/python2.7/threading.py", line 754, in run
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/opt/lib/python2.7/SocketServer.py", line 418, in __init__
  File "/opt/lib/python2.7/SocketServer.py", line 440, in server_activate
  File "/opt/lib/python2.7/socket.py", line 228, in meth
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Found domains: qnap.domain.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying qnap.domain.com...
::ffff:10.x.x.x - - [26/Jan/2019 15:53:56] "GET /.well-known/acme-challenge/0YFlo0oZlWlCAi<<<<<>>>>>>>>YKjrYiw8kf-LamM HTTP/1.1" 200 -
::xxx:xxx:xx:xxx - - [26/Jan/2019 15:53:58] "GET /.well-known/acme-challenge/0YFlo0oZlWlCAi<<<<<>>>>>>>>YKjrYiw8kf-LamM HTTP/1.1" 200 -
qnap.domain.com verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
wget: unrecognized option '--no-verbose'
BusyBox v1.27.2 () multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
        [--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
        [-S|--server-response] [-U|--user-agent AGENT] URL...

Retrieve files via HTTP or FTP

        --spider        Only check URL existence: $? is 0 if exists
        -c              Continue retrieval of aborted transfer
        -q              Quiet
        -P DIR          Save to DIR (default .)
        -S              Show server response
        -O FILE         Save to FILE ('-' for stdout)
        -U STR          Use STR for User-Agent header
        -Y on/off       Use proxy
`

**Comment by Yannik** [comment]
@OeveringIT Please install wget using `opkg install wget` or from the qnap app store (if it's available there).

**Comment by boevering** [comment]
That did the trick :) thanks @Yannik  🥇

**Comment by Yannik** [comment]
Great!
