### ISSUE TITLE
Problem when running renew_certificate.sh

### ISSUE THREAD

**Issue by prsltd** [Yannik/qnap-letsencrypt#57]
I'm getting the following error 

Checking whether to renew certificate on Tue, 14 May 2019 12:45:53 +0100
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 21952
/share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python2: can't open file 'acme-tiny/acme_tiny.py': [Errno 2] No such file or directory
An error occured. Restoring system state.
./renew_certificate.sh: line 6: 21952 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/letsencrypt/qnap-letsencrypt/tmp-webroot)

Am I missing a pre-requisite ?

**Comment by prsltd** [comment]
Forgot to add : This is on a TS453A, running QTS 4.3.6.0923

**Comment by Yannik** [comment]
yeah, you supposedly forgot to run the init script or executed it in the wrong directory.
