### ISSUE TITLE
errors with renew_certificate.sh

### ISSUE THREAD

**Issue by burbulence** [Yannik/qnap-letsencrypt#58]
**Platform/Firmware Information**

```
Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-453Be

Model = TS-X53B
Internal Model = TS-X53B
Version = 4.3.6
Build Number = 20190425
Rsync Model = QNAP
Build Date = 2019-04-25

```

**Is this the latest firmware for your device?**  Yes

 sh -x renew_certificate.sh
+ set -o errexit
+ trap cleanup ERR
++ date -R
+ echo 'Checking whether to renew certificate on Wed, 22 May 2019 09:12:48 +0100'
Checking whether to renew certificate on Wed, 22 May 2019 09:12:48 +0100
+ '[' -s letsencrypt/signed.crt ']'
+ python -c 'import SimpleHTTPServer'
++ /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf
+ /share/CACHEDEV1_DATA/.qpkg/Python/bin/python2 -c 'import SimpleHTTPServer'
++ /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf
+ /share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python2 -c 'import SimpleHTTPServer'
++ /sbin/getcfg Python Install_Path -f /etc/config/qpkg.conf
+ PYTHON=/share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python2
+ echo 'Renewing certificate...'
Renewing certificate...
+ echo 'Stopping Qthttpd hogging port 80..'
Stopping Qthttpd hogging port 80..
+ /etc/init.d/Qthttpd.sh stop
Shutting down Qthttpd services: OK.
+ mkdir -p tmp-webroot/.well-known/acme-challenge
+ cd tmp-webroot
+ pid=30704
+ cd ..
+ /share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python2 ../HTTPServer.py
+ echo 'Started python HTTP server with pid 30704'
Started python HTTP server with pid 30704
+ export SSL_CERT_FILE=cacert.pem
+ SSL_CERT_FILE=cacert.pem
+ /share/CACHEDEV1_DATA/.qpkg/Python/src/bin/python2 acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir tmp-webroot/.well-known/acme-challenge
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 418, in __init__
    self.server_activate()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Parsing account key...
Parsing CSR...
Found domains: mydomain.com
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying mydomain.com..
::ffff:11.22.33.445 - - [22/May/2019 09:13:04] "GET /.well-known/acme-challenge/FEAF3AnDCSuBWA8r18y-c3Ek-6PwYqSqKcUdFEYV41E HTTP/1.1" 200 -
::ffff:66.77.88.990 - - [22/May/2019 09:13:05] "GET /.well-known/acme-challenge/FEAF3AnDCSuBWA8r18y-c3Ek-6PwYqSqKcUdFEYV41E HTTP/1.1" 200 -
mydomain.com verified!
Signing certificate...
Certificate signed!
+ mv letsencrypt/signed.crt.tmp letsencrypt/signed.crt
+ echo 'Downloading intermediate certificate...'
Downloading intermediate certificate...
+ wget --no-verbose -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
2019-05-22 09:13:10 URL:https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem [1647/1647] -> "-" [1]
+ cat letsencrypt/signed.crt letsencrypt/intermediate.pem
+ echo 'Stopping stunnel and setting new stunnel certificates...'
Stopping stunnel and setting new stunnel certificates...
+ /etc/init.d/stunnel.sh stop
Shutting down apache proxy: OK
+ cat letsencrypt/keys/domain.key letsencrypt/chained.pem
+ cp letsencrypt/intermediate.pem /etc/stunnel/uca.pem
+ echo 'Done! Service startup and cleanup will follow now...'
Done! Service startup and cleanup will follow now...
+ cleanup
+ echo 'An error occured. Restoring system state.'
An error occured. Restoring system state.
+ '[' -n 30704 ']'
+ kill -9 30704
+ rm -rf tmp-webroot
renew_certificate.sh: line 6: 30704 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/homes/qnap-letsencrypt/tmp-webroot)
+ /etc/init.d/stunnel.sh start
Start apache proxy: OK
+ /etc/init.d/Qthttpd.sh start
Starting Qthttpd services: OK

I have the above output from the certificate renewal script. From what i can see there are 2 errors, the first being address already in use, and the second an error occurred.

My other concern is since running this script i've had numerous brute force attacks on my server.

**Comment by itemx** [comment]
You may want to check if something else than Qhttpd/fcgi-p is occupying your port 80?

ssh your NAS as admin and run "netstat -tlnp|grep 80" and you might see something, 
For example:

`tcp        0      0 :::80                   :::*                    LISTEN      2032/something`

The "2032" here is PID, kill that proc taking 80, and run the script again should work?

**Comment by avico78** [comment]
Same issue here ,
port 80 not in occupied .
also port 80 is open on router .

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 141, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/c5zdlbHg06WutLQ1t4ZhOV8CEsEO77xeMWb0K9mZM58, but couldn't download http://AAAAA.mqnapcloud.com/.well-known/acme-challenge/c5zdlbHg06WutLQ1t4ZhOV8CEsEO77xeMWb0K9mZM58:
An error occured. Restoring system state.
./renew_certificate.sh: line 6: 19339 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/AAAAA/ssl/qnap-letsencrypt/tmp-webroot)

**Comment by Hackroma974** [comment]
Hi ! ,

To First, thanks for your work Yannik. I have a same problem.. I supposed..

[/share/CACHEDEV1_DATA/Web/Letsencrypt/qnap-letsencrypt] # sudo ./renew_certificate.sh    
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 3847
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../HTTPServer.py", line 32, in servev4
    server = HTTPServer(('0.0.0.0', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 418, in __init__
    self.server_activate()
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/SocketServer.py", line 440, in server_activate
    self.socket.listen(self.request_queue_size)
  File "/share/CACHEDEV1_DATA/.qpkg/Python/src/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
**error: [Errno 98] Address already in use**

Parsing account key...
Parsing CSR...
Found domains: spiritualite-et-yoga.com, vivreauxpaysbas.com, qnap.atipx.fr, blue-sunset.art, atipx.fr, enoa-beaute.fr
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying atipx.fr...
::ffff:192.168.30.100 - - [13/Aug/2019 19:57:58] "GET /.well-known/acme-challenge/mKqRLoTuVWMIKIKb8FNcWCKxUEyiNF2kiJlgFW2-S4k HTTP/1.1" 200 -
atipx.fr verified!
Verifying blue-sunset.art...
::ffff:192.168.30.100 - - [13/Aug/2019 19:58:01] "GET /.well-known/acme-challenge/UQHIzSW-rY3r7VkkxXYAKFdzkHS2F-mgQMPMYAihcMA HTTP/1.1" 200 -
blue-sunset.art verified!
Verifying enoa-beaute.fr...
::ffff:192.168.30.100 - - [13/Aug/2019 19:58:03] "GET /.well-known/acme-challenge/OfMBlkcMqXPL28hRP_KbLM5oOARK9yDwteJIoiaJuFI HTTP/1.1" 200 -
enoa-beaute.fr verified!
Verifying qnap.atipx.fr...
::ffff:192.168.30.100 - - [13/Aug/2019 19:58:05] "GET /.well-known/acme-challenge/P_SibKd-uHam9jowQoX8UvhflD_GjSBVlBALTsx9u1M HTTP/1.1" 200 -
qnap.atipx.fr verified!
Verifying spiritualite-et-yoga.com...
::ffff:192.168.30.100 - - [13/Aug/2019 19:58:07] "GET /.well-known/acme-challenge/N71540iC6rF1KijWegHqRNojp_8sQZZdLz30r4viLKY HTTP/1.1" 200 -
spiritualite-et-yoga.com verified!
Verifying vivreauxpaysbas.com...
::ffff:192.168.30.100 - - [13/Aug/2019 19:58:09] "GET /.well-known/acme-challenge/xVllmeeziUF4HCNoUNR3XsXnAeqtQ83tyT-nDezU5Qw HTTP/1.1" 200 -
vivreauxpaysbas.com verified!
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
2019-08-13 19:58:14 URL:https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem [1647/1647] -> "-" [1]
Stopping stunnel and setting new stunnel certificates...
Shutting down apache proxy: OK
Done! Service startup and cleanup will follow now...
**An error occured. Restoring system state**.
./renew_certificate.sh: line 6:  3847 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/Web/Letsencrypt/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Starting Qthttpd services: OK

I do not understand the following two errors : **error: [Errno 98] Address already in use** and **An error occured. Restoring system state**. And I would like to know were the new certificates are stored. Thanks you !!

**Comment by vvranjek** [comment]
I have exactly the same problem. Any solution to this?

**Comment by JamesValero** [comment]
If the port is still in use, Qhttpd (QNAP Web GUI) may be using it still or if you ran the script multiple times, a previous run could be using up the port.

Run these commands to fix it
`netstat -anp|grep LISTEN\ | grep 80`

Look for something that looks like this:
`tcp        0      0 :::80                   :::*                    LISTEN      15143/python3`
The imprtant bit is the :80 and the numbers after LISTEN as that's the PID (process ID)

Now kill it (this example is 15143. Yours will be different)
`kill -9 15143`

Check if port 80 is still listening
`netstat -anp|grep LISTEN\ | grep 80`

You should no longer see the same type of line listed. Port 8080 may be listening and other various ports. That's okay. Leave those alone.

Try again.

**Comment by Yannik** [comment]
thanks, @JamesValero!

**Comment by Yannik** [comment]
With https://github.com/Yannik/qnap-letsencrypt/commit/20dba120032af6971f6b7bbd9add6a9c6b72b986, old python processes are automatically killed.
