### ISSUE TITLE
errors in renew_certificate

### ISSUE THREAD

**Issue by ittayd** [Yannik/qnap-letsencrypt#59]
I get tons of messages like this:
::ffff:192.168.2.194 - - [28/May/2019 09:12:37] "♥  ▒♥♥▒/▒▒▒▒▒y▒▒v#▒͐fD▒d▒▒c▒v▒▒▒ ▒◄▒Yr▒$~▒[▒▒l▒▒▒▒$=/㲪♣▒▒I▒▒▒ "" 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:37] code 400, message Bad request syntax ('\x16\x03\x01\x00\xb1\x01\x00\x00\xad\x03\x03\x13\xda/c9\\\x8b\xeb\xf5lt\xfe\x93\x8a\xfaI\xfd\xf6\xa4\xf8\xfe\x92\xfa\xbbC\xf9\xed\xa2\xeb')
::ffff:192.168.2.194 - - [28/May/2019 09:12:37] "♥ ▒  ▒♥♥▒/c9\▒▒▒lt▒▒▒▒I▒▒▒▒▒▒▒▒C▒▒▒▒" 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:38] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03K,gwut\xd5\xfd\x82\x85\x1aX\xfa8TF\x02z\xaa:\xfe\x8d\xfa\xfc\x9dej\xb1\xdf\x1c\xaf\xbd')
::ffff:192.168.2.194 - - [28/May/2019 09:12:38] "♥  ▒♥♥K,gwut▒▒▒▒X▒8TFz▒:▒▒▒▒▒ej▒▒▒▒ ▒◄▒Yr▒$~▒[▒▒l▒▒▒▒$=/㲪♣▒▒I▒▒▒ "♥▒+▒/▒,▒0̨̩▒▒ ▒ ▒ / 5 " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:38] code 400, message Bad request syntax ('\x16\x03\x01\x00\xb1\x01\x00\x00\xad\x03\x03\xd9\xde\xce,\xb4\xeb\xf8Q\x98)\x0e\x97\xb4\xe3K\xda[\x1c&\xdanl`\x93^\xbc9\xb4\x83N\xa5\x95\x00\x00\x1c') ::ffff:192.168.2.194 - - [28/May/2019 09:12:38] "♥ ▒  ▒♥♥▒▒▒,▒▒▒Q▒)▒▒▒K▒[&▒nl`▒^▒9▒▒N▒▒  " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x93T\xedD\xd6\xea\xb0w\x8b\x95\x15\x96\xe4^\xfb\x87/\x10\xc8\\\xdd\x19\xea]/_\xcc\xd3$F\x16\xdb')
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] "♥  ▒♥♥▒T▒D▒▒▒w▒▒▒▒^▒▒/►▒\▒↓▒]/_▒▒$F▒ ▒◄▒Yr▒$~▒[▒▒l▒▒▒▒$=/㲪♣▒▒I▒▒▒ "::♥▒+▒/▒,▒0̨̩▒▒ ▒ ▒ / 5 " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] code 400, message Bad request syntax ('\x16\x03\x01\x00\xb1\x01\x00\x00\xad\x03\x032a\xbb{j\xa9xfd>i')
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] "♥ ▒  ▒♥♥2a▒{j▒xfd>i" 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xe9nM\xf6\xd7m]\xb7\xee\xe0M\x08\xf1h0\xe7\xb0\xe8w#\x89\xa2v\xb5\xad\x95L\xf4\x04\xc3\x0fW')
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] "♥  ▒♥♥▒nM▒▒m]▒▒▒▒h0▒▒▒w#▒▒v▒▒▒L▒♦▒W ▒◄▒Yr▒$~▒[▒▒l▒▒▒▒$=/㲪♣▒▒I▒▒▒ "" 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] code 400, message Bad request version ('\xe4|\x01x\xe6\xc0r\xd4\xa1O\xee\x81\xff\xb3\x02\xf2\xb4\x00\x00\x1c\xba\xba\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00')
::ffff:192.168.2.194 - - [28/May/2019 09:12:39] "♥ ▒  ▒♥♥▒R▒▒▒v5▒ڬ:▒▒|x▒▒rԡO▒▒▒▒▒▒  ▒▒▒+▒/▒,▒0̨̩▒▒ ▒ ▒ / 5 " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd6I\\{U,\x9e\x8b\xb9\xd3+\xff\xc1+h]\xae^\x05\xd5$\xdd\x83\x9e0\x96U\xae\x0f\xfa\xc3\xa6')
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] "♥  ▒♥♥▒I\{U,▒▒▒▒+▒▒+h]▒^♣▒$݃▒0▒U▒▒æ ▒◄▒Yr▒$~▒[▒▒l▒▒▒▒$=/㲪♣▒▒I▒▒▒ "ZZ♥▒+▒/▒,▒0̨̩▒▒ ▒ ▒ / 5 " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x00\xa9\xef\xb1\xbe\x17xb\xb6r\xe8\x16\xf1l6esO\xb4l\xaby^$\x04')
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] "♥  ▒♥♥ ▒ﱾxb▒r▒▒l6esO▒l▒y^$♦" 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xb1\x01\x00\x00\xad\x03\x03\xef\xb0u\xe2K\xe3\xc0\xb7\xb1<\x86"\xc4_YI]\x8dhk')
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] "♥ ▒  ▒♥♥▒▒u▒K▒▒▒▒<▒"▒_YI]▒hk ▒▒▒▒}►x▒d▒▒  ▒▒▒+▒/▒,▒0̨̩▒▒ ▒ ▒ / 5 " 400 -
::ffff:192.168.2.194 - - [28/May/2019 09:12:41] code 400, message Bad request syntax ('\x16\x03\x01\x00\xb1\x01\x00\x00\xad\x03\x03\xa7\x82\xb9#d\xfc\xc5\xa9g=\xd1\xb5\xcbOG\xdc\xed\x8e\xc8\\@\x8bI\xea\xd9\x88qEG\xda\xda\xd9\x00\x00\x1c\x8a\x8a\xc0+\xc0/\xc0,\xc00\xcc\xa9\xcc\xa8\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00')

**Comment by Yannik** [comment]
You seem to have some bad encoding on your system.

**Comment by ittayd** [comment]
And how do I debug/resolve this "bad encoding"?
