### ISSUE TITLE
self-hosted webserver with public IP and goodaddy domain

### ISSUE THREAD

**Issue by kaneda79** [Yannik/qnap-letsencrypt#61]
Hi, I'm trying to obtain a certifcate for my website, hosted on my home server and accessible through a godaddy domain.

I see that when i put the request (manually, writing down the common name end asking to save the certificates on a folder on my pc) the procedure creates the ./well-known/ folder then fails wuith the following output:

#######################################
* [EROR] Preliminary validation failed
System.Net.WebException: Errore del server remoto: (403) Non consentito.
   in System.Net.HttpWebRequest.GetResponse()
   in PKISharp.WACS.Plugins.ValidationPlugins.HttpValidation`2.GetContent(Uri uri)
   in PKISharp.WACS.Plugins.ValidationPlugins.HttpValidation`2.WarmupSite()
   in PKISharp.WACS.Plugins.ValidationPlugins.HttpValidation`2.PrepareChallenge()
 [EROR] {
  "type": "urn:ietf:params:acme:error:unauthorized",
  "detail": "Invalid response from http://www.ilgiank.site/.well-known/acme-challenge/STsCQJBMMXAOnhugT7V2ySVjRwhoJL8ct2CBEEKF_Ek [50.63.202.55]: \"<!DOCTYPE html><body style=\\\"padding:0; margin:0;\\\"><html><head><meta name=\\\"viewport\\\" content=\\\"widt\"",
  "status": 403
}
 [EROR] Authorization result: invalid
 [EROR] Create certificate failed: Authorization failed

#######################################
I know the error is pretty generic, anyway i want to understand if my installation is fine to handle the procedure. Currently i host the website on a Windows 10 Pro, with WAMP installed and Wordpress (latest version).  Localhost and 127.0.0.1 point directly to the website. Outside the domain is tied to the public static IP the ISP assigned to me.

I even wanted to try the DNS authentication method, but I don't know how to use it with win-acme.

Thanks in advance!

**Comment by itemx** [comment]
I thought the script provided here is for obtain a SSL certification on "QNAP NAS" only.

imo above should belongs to https://github.com/PKISharp/win-acme if you said you are running a Windows 10 as server.

**Comment by Yannik** [comment]
As per @itemx, this only works with qnap.
