### ISSUE TITLE
Failing on wget

### ISSUE THREAD

**Issue by indyspike** [Yannik/qnap-letsencrypt#63]
**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-459U
Internal Model = TS-459
Version = 4.2.6
Build Number = 20190921
Rsync Model = QNAP
Build Date = 2019-09-21

```

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
Script is failing when trying to wget the cross-signed.pem certifiate:
```
wget --no-verbose -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem
OpenSSL: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

```
Changing the line to
```
wget --no-verbose --secure-protocol=TLSv1_2 -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem

```
works.

**Comment by Thana404** [comment]
Thanks @indyspike , your solution fixed my issue !

**Comment by phrogg** [comment]
Thanks, but after the edit I get another error:

```
OpenSSL: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
Unable to establish SSL connection.
```

**Comment by itemx** [comment]
It looks like the error codes are the same.

Have you replace all the wget command with an additional "--secure-protocol=TLSv1_2" verbose?
