### ISSUE TITLE
OpenSSL: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by phrogg** [Yannik/qnap-letsencrypt#64]
**Platform/Firmware Information**

```
Platform = X86_ATOM
Model = TS-439
Internal Model = TS-439
Version = 4.2.6
Build Number = 20191107
Rsync Model = QNAP
Build Date = 2019-11-07
```

**Is this the latest firmware for your device?**
Yes (4.2.6)
**Issue Summary (provide relevant error messages and log output):**
I get this error when running renew_certificate:
```
Downloading intermediate certificate...
ERROR: cannot verify letsencrypt.org's certificate, issued by ‘/C=TW/ST=Taipei/L=Taipei/O=QNAP Systems, Inc./OU=QTS/CN=QNAP NAS/emailAddress=support@qnap.com’:
  Self-signed certificate encountered.
    ERROR: certificate common name ‘QNAP NAS’ doesn't match requested host name ‘letsencrypt.org’.
To connect to letsencrypt.org insecurely, use `--no-check-certificate'.
```

**Comment by stpCES** [comment]
I've got the same QNAP Version 4.2.6 and it simply seems to be that the OpenSSL Version is still 1.0.1 not 1.0.2

**Comment by stpCES** [comment]
Hey phrogg,
I figured it out for my system. To ensure that you can use TLS 1.2  OpenSSL Version has to be at least v1.0.1 and wget 1.16. 
To force your system to use the newer TLS protocol alter the wget command in the reniew_certificate.sh file 
`wget --no-verbose -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem --secure-protocol=TLSv1_2`

**Comment by phrogg** [comment]
Thanks for the info, unfortunately however I can't test it right now. Because I have requested too many certificates for my domain :D @stpCES

**Comment by Yannik** [comment]
fixed in commit https://github.com/Yannik/qnap-letsencrypt/commit/df959753ba904c92f40ecbee27822bb7ce74fd16
