### ISSUE TITLE
certificate expired - renewal error

### ISSUE THREAD

**Issue by ash73** [Yannik/qnap-letsencrypt#66]
**Platform/Firmware Information**
Platform = MARVELL_6281
Model = TS-110
Internal Model = TS-119
Version = 4.2.5
Build Number = 20170413
Rsync Model = QNAP
Build Date = 2017-04-13

**Is this the latest firmware for your device?**
YES

**Issue Summary (provide relevant error messages and log output):**

I've been running the qnap-letsencrypt script on a QNAP for a couple of years.

Last month it failed to update the certificate and I only noticed yesterday when it expired.

If I run the script manually it gets as far as:
...
Signing certificate...
Certificate signed!
Downloading intermediate certificate...
OpenSSL: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
Unable to establish SSL connection.

Any suggestions?

p.s. OpenSSL on QNAP:
OpenSSL 1.0.1u  22 Sep 2016

**Comment by itemx** [comment]
Maybe it's the same thing to issue #63 
if the wget mentioned there doesn't work, try curl instead?

curl -s https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > letsencrypt/intermediate.pem

Should do the same thing.

**Comment by ash73** [comment]
That worked fine, many thanks!
