### ISSUE TITLE
kill: you need to specify whom to kill

### ISSUE THREAD

**Issue by dofuuz** [Yannik/qnap-letsencrypt#67]
**Platform/Firmware Information**

```
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-251+

Model = TS-X51
Internal Model = TS-X51
Version = 4.4.1
Build Number = 20191206
Rsync Model = QNAP
Build Date = 2019-12-06
```

**Issue Summary (provide relevant error messages and log output):**

Error occured during executing renew_certificate.sh

```
Killing old python processes hogging port 80
kill: you need to specify whom to kill
An error occured. Restoring system state.
```

It's fixed after changing this line
https://github.com/Yannik/qnap-letsencrypt/blob/20dba120032af6971f6b7bbd9add6a9c6b72b986/renew_certificate.sh#L41

to 

```sh
lsof -i tcp:80 -a -c python -t | xargs -r kill
```

**Comment by Yannik** [comment]
you are completely right. fixed!
