### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by kasi45** [Yannik/qnap-letsencrypt#7]
Thanks for the project
my proposed:
please using the same name conventions, as proposed and also use by "letsencrypt".
    privkey.pem - private key
    cert.pem - server cert only
    chain.pem - intermediates
    fullchain.pem - server cert + intermediates
cat cert.pem chain.pem privkey.pem > stunnel.pem
it is easier to understand  for laymen

this is a small error in your "readme.md"
cp ../openssl.cnf openssl-csr-conf.cnf  
you use in the rows after  : openssl-csr-config.cnf    

it is only cosmetic:
Is it possible to set explicit the commonName?
At the moment is used for the commonName the first in alphabetic order from the domainlist
xyz.dyndns.org
cloud.xyz.dyndns.org
www.xyz.dyndns.org

now in certificate for domain and subdomains
commonName:     cloud.xyz.dyndns.org  not  xyz.dyndns.org

sorry for the bad english. i hope you understand. ;-)
best regards 
kasi45

**Comment by kasi45** [comment]
Dear Yannik,
If the connection failed to letsencrypt, it was create an emty certificate.
I edit and insert some lines in your script 
this prevent an emty certificate.

`
python acme-tiny/acme_tiny.py --account-key letsencrypt/account.key --csr letsencrypt/domain.csr --acme-dir tmp-webroot/.well-known/acme-challenge > letsencrypt/cert.pem.temp

if [ -f letsencrypt/cert.pem.temp ] && [ -s letsencrypt/cert.pem.temp ] ; then
mv letsencrypt/cert.pem.temp letsencrypt/signed.crt
....
your code
....
fi

kill -9 $pid || true
rm -rf tmp-webroot
/etc/init.d/Qthttpd.sh start
`
best regards
kasi45

**Comment by Yannik** [comment]
@kasi45 Could you explain under what circumstances the connection to letsencrypt may fail? Their infrastructure is pretty redundant from what I know. That seems like kind of a edge case. Aditionally, could you open 2 seperate pull requests for your suggestions, please.

**Comment by kasi45** [comment]
Thank you for your answere!
The empty certificate was not a problem with letsencrypt. There was errors by myself. For once on my firewall port 80 was closed and another time my router configuration was flawed. 
The "if" construct prevented the override of a still existing old, but valid certificates by user errors.
I open port 80 only when i renew the certificates.

best regards
kasi45
