### ISSUE TITLE
"Malware Remover" by QNAP will comment out the crontab for this script.

### ISSUE THREAD

**Issue by itemx** [Yannik/qnap-letsencrypt#71]
Just noticed the "Malware Remover" by QNAP will comment out the crontab set for qnap-letsencrypt.
Already sent a ticket to them regarding their behaviors. But does not receive a clear response if they will fix it in malware remover.

Before that, I think the only option is to execute the renew_certificate manually, or disable the malware remover.

Maybe it will be nice to notice people about this in the README.md

**Comment by itemx** [comment]
Updates after some tests:

After some cross checks for items inside crontab, seems full path can survive after MR scan.
So, if we modify the crontab like below, 

30 2 * * * /path/to/the/renew_certificate.sh >> /path/to/the/renew_certificate.log 2>&1

It will not be commented after scan.

Tested on an TS-1277, Malware Remover 4.5.5.0

**Comment by itemx** [comment]
Tested on TS-1277 and TBS-453A it seems working.

**Comment by Yannik** [comment]
@itemx Can you confirm that https://github.com/Yannik/qnap-letsencrypt/commit/f5cf387922682cd84a0d7ba042d7647a4929ad3e fixes this?

**Comment by itemx** [comment]
Thanks for the fix. From my machine:

First check: if this line survives after malware scanner's scan.

-> Pass

Second check: "./renew_certificate.log"

-> NG

the "./" will result the renew_certificate.log appears in somewhere else
(possible the root of file system) instead of its original place.

I'll suggest to use full path pointing renew_certificate.log in order to avoid surprises.

from your commit as example, this should work well (although somehow ugly)

30 3 * * * /share/CE_CACHEDEV1_DATA/qnap-letsencrypt/renew_certificate.sh >> /share/CE_CACHEDEV1_DATA/qnap-letsencrypt/renew_certificate.log 2>&1

The dev team of Malware Remover said they'll consider to whitelist the "cd" command, but not guarantee that will happen or not in the future.

**Comment by itemx** [comment]
I've also figured out some path errors, maybe there's something related parts in the python code also?

`[~] # tail renew_certificate.log
Checking whether to renew certificate on Mon, 16 Mar 2020 17:33:07 +0800
Renewing certificate...
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 2431
/share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 34: letsencrypt/signed.crt.tmp: No such file or directory
/share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3: can't open file '../HTTPServer.py': [Errno 2] No such file or directory
`

**Comment by itemx** [comment]
Sorry for separate the posts, after I updated to your latest code, the output becomes much more:

I think most of the error is from " No such file or directory "  which the script can not find proper file from path issues.

> [~] # cat /share/homes/cert/qnap-letsencrypt/renew_certificate.log
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 1: et: command not found
> Checking whether to renew certificate on Mon, 16 Mar 2020 17:46:04 +0800
> Renewing certificate...
> Stopping Qthttpd hogging port 80..
> Shutting down Qthttpd services: OK.
> Killing old python processes hogging port 80
> Started python HTTP server with pid 17043
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 50: letsencrypt/signed.crt.tmp: No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 5: 17043 Killed                  "$PYTHON" ../HTTPServer.py  (wd: ~/tmp-webroot)
> Start apache proxy: OK
> Starting Qthttpd services: OK
> mv: can't rename 'letsencrypt/signed.crt.tmp': No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Starting Qthttpd services: OK
> Downloading intermediate certificate...
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 53: letsencrypt/intermediate.pem: No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Starting Qthttpd services: OK
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 54: letsencrypt/chained.pem: No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Starting Qthttpd services: OK
> Stopping stunnel and setting new stunnel certificates...
> Shutting down apache proxy: rm: can't remove '/var/lock/apache_proxys.pid': No such file or directory
> OK
> cat: letsencrypt/keys/domain.key: No such file or directory
> cat: letsencrypt/chained.pem: No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Recover apache confiugre
> Starting Qthttpd services: OK
> cp: cannot stat `letsencrypt/intermediate.pem': No such file or directory
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Recover apache confiugre
> Starting Qthttpd services: OK
> Done! Service startup and cleanup will follow now...
> An error occured. Restoring system state.
> /share/homes/cert/qnap-letsencrypt/renew_certificate.sh: line 7: kill: (17043) - No such process
> Start apache proxy: OK
> Recover apache confiugre
> Starting Qthttpd services: OK
>

**Comment by Yannik** [comment]
Okay.. that's quite a few issues. I've reverted to commit which modified the cronjob for now.

Would you be interested in providing a PR which includes all the necessary changes?

**Comment by itemx** [comment]
It might take some time and I am not really familiar with Python. Guess I can have some look on Weekend?

**Comment by Yannik** [comment]
@itemx That would be great!

**Comment by itemx** [comment]
@Yannik the PR is created. I just did some simple tests but it is working without error messages on my device. Afterall I just play with the shell scripts instead of python codes. :p

**Comment by Yannik** [comment]
fixed by commit #73
