### ISSUE TITLE
Rollback script cause getting "Not found"

### ISSUE THREAD

**Issue by gsegatori** [Yannik/qnap-letsencrypt#72]
**Platform/Firmware Information**

```
Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-653B
Model = TS-X53B
Internal Model = TS-X53B
Version = 4.4.1
Build Number = 20200214
Rsync Model = QNAP
Build Date = 2020-02-14
```

**Is this the latest firmware for your device?**
yes
**Issue Summary (provide relevant error messages and log output):**
After running the script it worked, but after a reboot I cannot access to webconsole anymore (from the lan or the wan) I got `Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`

**Comment by Yannik** [comment]
Did you get my email?

**Comment by gsegatori** [comment]
Received but gmail had put on spam (that's crazy really)

**Comment by Yannik** [comment]
Close due to inactivity
