### ISSUE TITLE
servev4only function will not be called, when NAS only use IPv4.

### ISSUE THREAD

**Issue by ssdoz2sk** [Yannik/qnap-letsencrypt#74]
**Platform/Firmware Information**
I find a bug, but I don't want to create a pull request. 

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**

In `HTTPServer.py` main function, it try to call serve function. But serve function ignore the error (`errno.EAFNOSUPPORT`), main function could not catch the error. servev4only function is useless. 

https://github.com/Yannik/qnap-letsencrypt/blob/22eb5a621ba5bfdf8946d24aea8c0d87b45342b3/HTTPServer.py#L10-L16

https://github.com/Yannik/qnap-letsencrypt/blob/22eb5a621ba5bfdf8946d24aea8c0d87b45342b3/HTTPServer.py#L23-L27

**Comment by Yannik** [comment]
You're right, thanks for the report. I've fixed it.
