### ISSUE TITLE
-sh: letsencrypt/domain.csr: No such file or directory

### ISSUE THREAD

**Issue by daledali** [Yannik/qnap-letsencrypt#75]
**Platform/Firmware Information**

```
Run
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["

and paste it here!
```

**Is this the latest firmware for your device?**

**Issue Summary (provide relevant error messages and log output):**

Not sure what I'm doing wrong. What should be typed into qnap putty and what should be typed into windows cmd?

https://pastebin.com/0qzHS1ed

[~] # grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-251+
[~] # grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
Model = TS-X51
Internal Model = TS-X51
Version = 4.4.1
Build Number = 20200214
Rsync Model = QNAP
Build Date = 2020-02-14
[~] # openssl req -new -sha256 -key letsencrypt/keys/domain.key -subj "/CN=192.168.86.9" > letsencrypt/domain.csr
-sh: letsencrypt/domain.csr: No such file or directory
[~] # openssl req -new -sha256 -key letsencrypt/keys/domain.key -subj "/CN=192.168.86.9" > letsencrypt/domain.csr
[~] #

**Comment by daledali** [comment]
[~] # mv /etc/stunnel/stunnel.pem /etc/stunnel/stunnel.pem.orig
mv: can't rename '/etc/stunnel/stunnel.pem': No such file or directory
[~] #

**Comment by Yannik** [comment]
First you are executing openssl commands inside an openssl prompt:

```
[~] # openssl
OpenSSL> openssl req -new -sha256 -key letsencrypt/keys/domain.key -subj "/CN=nas.xxx.de" > letsencrypt/domain.csr
```

Then you left the openssl directory: `[/share/Web/ssl_cert] # cd` which leads all other commands to fail.

It seems like you are new to linux-based operating systems. Frankly, this exceeds what github issues are for, as this is not an issue with `qnap-letsencrypt`. 
I can offer to set this up for you or teach you on how to do it yourself. Feel free to shoot me an email if you're interested.
