### ISSUE TITLE
Certificate renew only for qnap web interface

### ISSUE THREAD

**Issue by quintos85** [Yannik/qnap-letsencrypt#78]
i ' have a question,

Is it normal for the certificate to be renewed only on the QNAP webSite? By logging into FTP, I don't see the new certificate but the old one.

Regards

i post images for major details

when i connect to the my qnap website i see the new certificate

![immagine](https://user-images.githubusercontent.com/20645038/80701044-0c7bc700-8adf-11ea-86ee-9bcd4d931471.png)

but in the security tab i see the old certificate
![immagine](https://user-images.githubusercontent.com/20645038/80701114-2a492c00-8adf-11ea-9d63-368f273f6412.png)

and when i connect via ftp client i see the old certificate warning...

![immagine](https://user-images.githubusercontent.com/20645038/80701258-67152300-8adf-11ea-9f3d-9791e43b66d9.png)

**Comment by Yannik** [comment]
Yes, that's normal.

**Comment by quintos85** [comment]
ah ok, how can i copy the certificate also for ftp?

**Comment by Yannik** [comment]
I don't know

**Comment by quintos85** [comment]
i tried searching in "proftpd.conf" and found this:

![immagine](https://user-images.githubusercontent.com/20645038/80711302-6e90f800-8af0-11ea-8b96-a030d69d5dea.png)

it's possible?

**Comment by Yannik** [comment]
Just try it out :-) Maybe it works.

**Comment by quintos85** [comment]
ok :), thank you for your help

**Comment by quintos85** [comment]
hello,
I have found the solution. By copying and renaming the files:

signed.crt -> backup.cert

and

domain.key -> backup.key

and everything seems to work, both the ftp certificate and the qnap security page are updated

**Comment by Yannik** [comment]
@quintos85 Ok, good. I made a commit to support ftp: https://github.com/Yannik/qnap-letsencrypt/commit/4bf3a0ecd3ebf0c835961795ec36583bc7a45d96

Can you please check this (use `git pull`) and report back if it works?

**Comment by quintos85** [comment]
ok,

tomorrow i try the code and report back if it works.

Thank you very much.

**Comment by quintos85** [comment]
hello,

i have tried the script, but get an error during stop or start ftp service ... i dont know. I investigate the problem

**Comment by quintos85** [comment]
good morning,

i'he investigated, and supect the ftp start\stop script return a "non standard" return value. I have try to stop normaly the service, all ok the service is correctly stopped, but the return value is 1.

![immagine](https://user-images.githubusercontent.com/20645038/81041504-4a496880-8eae-11ea-953d-19fee8db29a6.png)

is it possible that this value is considered by the script as an error(with set -o options)?

thank you

**Comment by Yannik** [comment]
@quintos85 Can you also check `/etc/init.d/ftp.sh start`; echo $?` please.

**Comment by quintos85** [comment]
yes,
this is the result:
![immagine](https://user-images.githubusercontent.com/20645038/81051703-7e2e8900-8ec2-11ea-9c9f-c6b68d6c64ac.png)

**Comment by Yannik** [comment]
@quintos85 Please test my latest commit: https://github.com/Yannik/qnap-letsencrypt/commit/6afabddcee4f23f29df008f62c7296e7f2c96511

**Comment by quintos85** [comment]
YESSSS!!!!

We are the champion!!! in this way all WORKS!!!

Thank you very much!!

**Comment by Yannik** [comment]
Ok, good!
