### ISSUE TITLE
I Dont get it 

### ISSUE THREAD

**Issue by KatzeMau** [Yannik/qnap-letsencrypt#81]
Could You please make a youtube tutorial, i dont find the error
**Platform/Firmware Information**

```
[/share/letsenqrypt/qnap-letsencrypt] # grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf
[System]
Model = TS-X31P2
Internal Model = TS-X41
Version = 4.4.2
Build Number = 20200519
Rsync Model = QNAP
Build Date = 2020-05-19
[Test]
[NTP]
[Alert]
[Network]
[bond0]
[eth0]
[eth1]
[Samba]
[Appletalk]
[SNMP]
[WebFS]
[QWEB]
[QPHOTO]
[BTDownload]
Version = 1.0
[NVR]
[Storage]
[Disk]
[FTP]
[DHCP Server]
[Printers]
[LOGO]
[UPS]
[Misc]
[HWTEST]
[MySQL]
[LOGIN]
[Index]
[iSCSI]
Model Name = TS-X31P2
[END_FLAG]
[Ban Engine]
[Network Recycle Bin]
[SDM]
[PgSQL]
[/share/letsenqrypt/qnap-letsencrypt] # | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
-sh: syntax error near unexpected token `|'
[/share/letsenqrypt/qnap-letsencrypt] # grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["

```

**Is this the latest firmware for your device?**
Yes

**Issue Summary (provide relevant error messages and log output):**
[/share/letsenqrypt/qnap-letsencrypt] # sh renew_certificate.sh
BusyBox v1.01 (2020.05.18-19:14+0000) multi-call binary

Usage: readlink

Displays the value of a symbolic link.

Checking whether to renew certificate on Tue, 09 Jun 2020 21:20:47 +0200
Renewing certificate...
qnap-letsencrypt version: f758272
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 3541
Serving v4 only
Parsing account key...
Parsing CSR...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 91, in get_crt
    out = _cmd(["openssl", "req", "-in", csr, "-noout", "-text"], err_msg="Error loading {0}".format(csr))
  File "acme-tiny/acme_tiny.py", line 28, in _cmd
    raise IOError("{0}\n{1}".format(err_msg, err))
OSError: Error loading letsencrypt/domain.csr
b"letsencrypt/domain.csr: No such file or directory\n1979524304:error:02001002:system library:fopen:No such file or directory:bss_file.c:413:fopen('letsencrypt/domain.csr','r')\n1979524304:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:415:\n"
An error occured. Restoring system state.
Start apache proxy: OK
Recover apache confiugre
Starting Qthttpd services: Qthttpd.
[/share/letsenqrypt/qnap-letsencrypt] #

**Comment by Yannik** [comment]
You need to follow the guide: https://github.com/Yannik/qnap-letsencrypt#setting-up-qnap-letsencrypt

You did not do step 2.
