### ISSUE TITLE
Too many arguments genrsa

### ISSUE THREAD

**Issue by ciltocruz** [Yannik/qnap-letsencrypt#84]
**Platform/Firmware Information**

Model = HS-251
Internal Model = HS-251
Version = 4.4.2
Build Number = 20200529
Rsync Model = QNAP
Build Date = 2020-05-29

Hello.

Hi. I have installed this software yesterday. When I run: "./init.sh" this appears.

`Generating RSA private key, 4096 bit long modulus (2 primes)`
`...............................................................................++++`
`.........................................++++`
`e is 65537 (0x010001)`
`Extra arguments given.`
`genrsa: Use -help for summary.`

It seems that genrsa does not support "-sha256" at the end of the line.

How can I solve it?

Thank you.

**Comment by Yannik** [comment]
Whats the output of `openssl version` for you?

**Comment by ciltocruz** [comment]
OpenSSL 1.1.1g  21 Apr 2020

**Comment by Yannik** [comment]
Okay. Please try my latest commit using `git pull`.

**Comment by ciltocruz** [comment]
It works!!!! 

I will continue with the process.

Can I generate wildcards with this program?

**Comment by Yannik** [comment]
No, as this only supports the HTTP-01 challenge, which does not support wildcard certs.
