### ISSUE TITLE
invalid public key in CSR: key length wasn't a multiple of 8: 4069

### ISSUE THREAD

**Issue by stoffpalette** [Yannik/qnap-letsencrypt#85]
**Platform/Firmware Information**

```
Platform = X86_PINEVIEW
Model = TS-259
Internal Model = TS-259
Version = 4.2.6
Build Number = 20200611
Rsync Model = QNAP
Build Date = 2020-06-11
```

**Is this the latest firmware for your device?** 
YES
**Issue Summary (provide relevant error messages and log output):**

This is the log-output (replaced the payload string with \<STRING-WITH-2010-BYTES-HERE\>):

`Signing certificate...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 156, in get_crt
    _send_signed_request(order['finalize'], {"csr": _b64(csr_der)}, "Error finalizing order")
  File "acme-tiny/acme_tiny.py", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error finalizing order:
Url: https://acme-v02.api.letsencrypt.org/acme/finalize/90072266/3980879987
Data: b'{"payload": "<STRING-WITH-2010-BYTES-HERE>", "signature": "s00FDYHi3PKLqBDQfN8U7UA9o_-u5CpMEzz89bPeg8mig2cYV4IeeJTfLFpXJPp3zKIJlxNDwIXcKTpuY2CwXy63OXSFfsYEW9FXQ_P5pz-rt8yYLnwYfOKj-rmYV4O02uek_c1uhCZTQ59pfVMw8cLTrJXnwnu-W64rTV6rjeDrA2-HSgNTKQwS5vhpL7MU1GaD2SAb5frAcV4pLoYMGVZi2197m278dEnyOGiAMGC7LVA3UJL11QjXZUv1NmQ2j6wo2nXIbffgSHB36c7Odn5lseaCtldE5Qn3X4YkTsToxZUeFdp-NZ4qGQUM1DkhYn1VOrI0DxfYDt_9u-mul7jCpAAANPNm9cntgDySkJ13C-vVvxnz9DlDaAjX2FMWYOqcYa4qHpj3XKhqs_gO-yQzTFCkqH5HYNUNs3ZQkHctBzjaFoXXBOwFhs48DA_AdGbEtn4zQqDmgefl-Zq8vmAAEZXoGX92ZLdH6X-9fCNz3M9gJImsmPKhNOYADLYZmJHOmeRQoJQ-cWOswW3kCTL3J2R35vU7DDqhjXK32uvd3_J6pZfw81G_q0f02f1PCd-b6ni_mTVVyxOIt8wYIcyPVE7D9TNJDhIVhIdL2fxoyMqL9A4D22Npu379N-OyODtBN834j9c7YkUhhRq4uP-jk7W5MEPDzCaf7NECmPg", "protected": "eyJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC85MDA3MjI2NiIsICJub25jZSI6ICIwMDAyTWczc2l2U19iZFMwWlNaMU1Xa2hPaG9GYUxXMWZJUlNic2pLNWJEWnR4dyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvZmluYWxpemUvOTAwNzIyNjYvMzk4MDg3OTk4NyIsICJhbGciOiAiUlMyNTYifQ"}'
Response Code: 400
Response: {'type': 'urn:ietf:params:acme:error:badPublicKey', 'detail': "Error finalizing order :: invalid public key in CSR: key length wasn't a multiple of 8: 4069", 'status': 400}
An error occured. Restoring system state.
./renew_certificate.sh: line 11: 13194 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/homes/admin/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Recover apache confiugre
Starting Qthttpd services: Qthttpd.
`

**Comment by Yannik** [comment]
You're completely right, there was a typo in my latest commit. It's now fixed. Please `git pull`.

**Comment by stoffpalette** [comment]
Thanks for your fast reply!
Just pulled and executed renew_certificate - _the same error still occurs_.
Can you please check once more?...
