### ISSUE TITLE
IndexError: list index out of range An error occured. Restoring system state. ./renew_certificate.sh: line 11: 10652 Killed 

### ISSUE THREAD

**Issue by Daniel-Irvine** [Yannik/qnap-letsencrypt#86]
**Platform/Firmware Information**

```
Run
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["

and paste it here!
```
Platform = X86_CEDAVIEW
DISPLAY_NAME = TS-269 Pro

Model = TS-269
Internal Model = TS-269
Version = 4.3.4
Build Number = 20200408
Rsync Model = QNAP
Build Date = 2020-04-08
[/share/qnap-letsencrypt/qnap-letsencrypt/qnap-letsencrypt] #

**Is this the latest firmware for your device?** Yes

**Issue Summary (provide relevant error messages and log output):**
When I run the ./renew_certificate.sh script it trows an error list index out of range.

Output is below :+1: 

[/share/qnap-letsencrypt/qnap-letsencrypt/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Sun, 05 Jul 2020 12:11:34 +0200
Renewing certificate...
qnap-letsencrypt version: 79e6e4e
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 10652
Parsing account key...
Parsing CSR...
Found domains: *.irvine-banning.eu, *.irvine-banning.nl
Getting directory...
Directory found!
Registering account...
Registered!
Creating new order...
Order created!
Verifying irvine-banning.eu...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 131, in get_crt
    challenge = [c for c in authorization['challenges'] if c['type'] == "http-01"][0]
IndexError: list index out of range
An error occured. Restoring system state.
./renew_certificate.sh: line 11: 10652 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/qnap-letsencrypt/qnap-letsencrypt/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Recover apache confiugre
Starting Qthttpd services: OK

Before starting I made sure both www.irvine-banning.nl and www.irvine-banning.eu are reachable on port 80 
Any ideas how to fix this are most welcome as I need renewal of the certs by july 11 2020.
Dan

**Comment by Yannik** [comment]
Maybe try updating acme-tiny? This does not seem to be an issue with qnap-letsencrypt.

**Comment by Yannik** [comment]
Oh, you're trying to issue wildcard certs. That is not possible with the HTTP-01 challenge.

**Comment by Daniel-Irvine** [comment]
Ah, now I understand. I used to be able to get these for free via sslforfree.com using DNS validation, however they stopped the free service 2 months ago. So I'm now looking for alternatives. 
I can obtain just the www. domain names for the webservers. I can next try the Xeams option to get one for the mailserver. 
I'd prefer using the wildcard as it's simpler to just use one file.   
Thanks Dan
