### ISSUE TITLE
SCRIPT_DIR not found

### ISSUE THREAD

**Issue by quintos85** [Yannik/qnap-letsencrypt#89]
Hi everyone,

In my Qnap this line is not interpreted in the script: "renew_certificate.sh"

SCRIPT_DIR = $ (dirname "$ (readlink -f -" $ 0 ")")
cd "$ SCRIPT_DIR"

I changed it to:

SCRIPT_DIR = $(dirname "$0")

and now the script seems to work.

I don't know if it can be considered a problem. But I remain available for further clarification

**Comment by Yannik** [comment]
@quintos85 Can you provide the output of the following commands:


```
grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.conf | grep -v "\[System\]" | awk '1;/\[/{exit}' |grep -v "\["
```

**Comment by quintos85** [comment]
Good Morning Yannik.

Sure :   

grep -e ^Platform -e ^DISPLAY_NAME  /etc/platform.conf
Platform = MARVELL_6281

grep -e ^Version -e ^Build -e Model -e "\[" /etc/default_config/uLinux.c>
Model = TS-212
Internal Model = TS-219
Version = 4.3.3
Build Number = 20200821
Rsync Model = QNAP
Build Date = 2020-08-21

**Comment by BstAA** [comment]
I've got the same problem and this isn't solved by using "dirname"

Platform = MARVELL_6281
Model = TS-410
Internal Model = TS-419
Version = 4.2.6
Build Number = 20200821
Rsync Model = QNAP
Build Date = 2020-08-21

Short test-script:
`[/opt/certbot/qnap-letsencrypt] # cat short.sh
#!/usr/bin/env bash
set -o errexit

trap error_cleanup ERR

error_cleanup() {
  echo "An error occured. Restoring system state."
  cleanup
}

cleanup() {
  [ -n "$pid" ] && kill -9 $pid
  rm -rf tmp-webroot
  /etc/init.d/stunnel.sh start
  /etc/init.d/Qthttpd.sh start
}

SCRIPT_DIR=$(dirname "$(readlink -f -- "$0")")
cd "$SCRIPT_DIR"
`

Run script from /root

`[~] # /opt/certbot/qnap-letsencrypt/short.sh
BusyBox v1.01 (2020.08.21-05:06+0000) multi-call binary

Usage: readlink

Displays the value of a symbolic link.

[~] #
`

**Comment by quintos85** [comment]
> 
> 
> I've got the same problem and this isn't solved by using "dirname"
> 
> Platform = MARVELL_6281
> Model = TS-410
> Internal Model = TS-419
> Version = 4.2.6
> Build Number = 20200821
> Rsync Model = QNAP
> Build Date = 2020-08-21
> 
> Short test-script:
> `[/opt/certbot/qnap-letsencrypt] # cat short.sh
> #!/usr/bin/env bash
> set -o errexit
> 
> trap error_cleanup ERR
> 
> error_cleanup() {
> echo "An error occured. Restoring system state."
> cleanup
> }
> 
> cleanup() {
> [ -n "$pid" ] && kill -9 $pid
> rm -rf tmp-webroot
> /etc/init.d/stunnel.sh start
> /etc/init.d/Qthttpd.sh start
> }
> 
> SCRIPT_DIR=$(dirname "$(readlink -f -- "$0")")
> cd "$SCRIPT_DIR"
> `
> 
> Run script from /root
> 
> `[~] # /opt/certbot/qnap-letsencrypt/short.sh
> BusyBox v1.01 (2020.08.21-05:06+0000) multi-call binary
> 
> Usage: readlink
> 
> Displays the value of a symbolic link.
> 
> [~] #
> `
> **--> no cd after script!**

Hello @BstAA,

I don't understand.  You tried to change this line in the script:

SCRIPT_DIR = $ (dirname "$ (readlink -f -" $ 0 ")")

in this:

SCRIPT_DIR = $ (dirname "$ 0")

?

because it works for me

**Comment by BstAA** [comment]
@quintos85: It didn't work for me, as I have a different (older) operating system :-(
But meanwhile I found a more general solution and an important hint.

1. Hint in bash faq "[How do I determine the location of my script](http://mywiki.wooledge.org/BashFAQ/028)?"
Important quote from there

> Before we dive into solutions, let's clear up some misunderstandings. It is important to understand that:
> Your script does not actually have a location! Wherever the bytes end up coming from, there is no "one canonical path" for it. Never.
>$0 is NOT the answer to your problem. If you think it is, you can either stop reading and write more bugs, or you can accept this and read on.
2. One more general possible solution: "[How to get the source directory of a Bash script from within the script itself?"](https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself)

```
# pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do cd `dirname "$SCRIPT_PATH"`; SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;

echo "Script_path: $SCRIPT_PATH"
echo "\$0: $0"
echo "pwd: `pwd`"

# popd  > /dev/null
```
The `popd` and `pushd` command are only for test purposes to get back to the caller 

This will always give the full path i.e. when called by:
```
- bash /full/path/to/script.sh
- ./script.sh
- /full/path/to/script.sh
- ./short_link.sh (where `short_link.sh` is a symbolic link to `/full/path/to/script.sh`)
```
Testing especially the last one shows the problem of using `$0`

@Yannik : I am not (yet) trained in using git / pull requests but I propose to use this enhancement to be more system independent.
