### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by aetasoul** [Yannik/qnap-letsencrypt#91]
Hi @Yannik I has recived this email from Let's Encrypt:

**Subject**: Update your client software to continue using Let's Encrypt

Hi,

According to our records, your Let's Encrypt software client renewed a TLS/SSL certificate recently using the ACMEv1 protocol. Here are the details of one recent ACMEv1 request from each of your account(s):

**PRIVATE INFORMATIONS**

On June 1, 2021, you will no longer be able to renew your certificates using ACMEv1. You should upgrade to an ACMEv2 compatible client before then, or certificate issuance will fail. For most people, simply upgrading to the latest version of your existing client will suffice. You can view the client list at: https://letsencrypt.org/docs/client-options/

ACMEv1 API deprecation details can be found in our community forum: 
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1
___

The question that I have for you is:
*  You script actually support the ACMEv2 certificates or I have to upgrade something?

Thanks.

**Comment by Yannik** [comment]
The latest version of this script and acme-tiny do support acmev2, you just need to update.
