### ISSUE TITLE
renew_certificate.sh returning an error <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by gsegatori** [Yannik/qnap-letsencrypt#92]
**Platform/Firmware Information**

```
Platform = X86_APOLLOLAKE
DISPLAY_NAME = TS-653B

Model = TS-X53B
Internal Model = TS-X53B
Version = 4.4.3
Build Number = 20200925
Rsync Model = QNAP
Build Date = 2020-09-25

```

**Is this the latest firmware for your device?**
Yes
**Issue Summary (provide relevant error messages and log output):**
[/share/CACHEDEV2_DATA/Public/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Thu, 15 Oct 2020 21:57:23 +0200
Renewing certificate...
qnap-letsencrypt version: 79e6e4e
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 4237
Parsing account key...
Parsing CSR...
Found domains: mydomain.xxx.xx
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying mydomain.xxx.xx...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 141, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://mydomain.xxx.xx/.well-known/acme-challenge/aetGdjdUNO_tIQBCNRxYY4829rgyQN3Ferc2XpSXnvk
Data: None
Response Code: None
Response: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/aetGdjdUNO_tIQBCNRxYY4829rgyQN3Ferc2XpSXnvk, but couldn't download http://mydomain.xxx.xx/.well-known/acme-challenge/aetGdjdUNO_tIQBCNRxYY4829rgyQN3Ferc2XpSXnvk: Error:
Url: http://mydomain.xxx.xx/.well-known/acme-challenge/aetGdjdUNO_tIQBCNRxYY4829rgyQN3Ferc2XpSXnvk
Data: None
Response Code: None
Response: <urlopen error [Errno 111] Connection refused>
An error occured. Restoring system state.
./renew_certificate.sh: line 11:  4237 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV2_DATA/Public/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Starting Qthttpd services: Qthttpd.
[/share/CACHEDEV2_DATA/Public/qnap-letsencrypt] #

**Comment by Yannik** [comment]
The problem is clear: your host is not reachable on port 80 from the internet.

**Comment by gsegatori** [comment]
Thank you, I forgot to put the rule port forwarding 80 in the router
