### ISSUE TITLE
Unable to find remote helper for 'https' when cloning

### ISSUE THREAD

**Issue by ChasonDeshotel** [Yannik/qnap-letsencrypt#94]
Per instructions

```
/share/CACHEDEV1_DATA/.ssl] # git clone https://github.com/Yannik/qnap-letsencrypt.git
Cloning into 'qnap-letsencrypt'...
fatal: Unable to find remote helper for 'https'
```
I switched https for git:

`git clone git://github.com/Yannik/qnap-letsencrypt.git`

and it succeeded

Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-451+
Model = TS-X51
Internal Model = TS-X51
Version = 4.4.3
Build Number = 20200925
Rsync Model = QNAP
Build Date = 2020-09-25

**Comment by Yannik** [comment]
How did you install git?

**Comment by Yannik** [comment]
close due to inactivity

**Comment by ChasonDeshotel** [comment]
I used Entware and the fix is to `opkg install git-http` for the http helper and `opkg install ca-bundle` may be necessary for https
