### ISSUE TITLE
python3: can't open file 'acme-tiny/acme_tiny.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ChasonDeshotel** [Yannik/qnap-letsencrypt#95]
```[/share/CACHEDEV1_DATA/.ssl/qnap-letsencrypt] # sh renew_certificate.sh
Checking whether to renew certificate on Thu, 19 Nov 2020 22:29:37 -0600
Renewing certificate...
qnap-letsencrypt version: 79e6e4e
Using python path: python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 22169
python3: can't open file 'acme-tiny/acme_tiny.py': [Errno 2] No such file or directory
An error occured. Restoring system state.
renew_certificate.sh: line 11: 22169 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/.ssl/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Starting Qthttpd services: OK
```

Platform = X86_BAYTRAIL
DISPLAY_NAME = TS-451+
Model = TS-X51
Internal Model = TS-X51
Version = 4.4.3
Build Number = 20200925
Rsync Model = QNAP
Build Date = 2020-09-25

**Comment by ChasonDeshotel** [comment]
Turns out this is related to the last issue I posted however init.sh should croak here which is I guess a bug in its own right

```[/share/CACHEDEV1_DATA/.ssl/qnap-letsencrypt] # sh init.sh
Cloning into 'acme-tiny'...
fatal: Unable to find remote helper for 'https'
```

So it looks like I have to figure out what ssl libraries are missing to install git with ssl support

**Comment by ChasonDeshotel** [comment]
Nevermind that seemed like work. Solved this the same way as the other: replaced https with git

`git clone git://github.com/diafygi/acme-tiny.git`

After that everything worked great! :D

**Comment by Yannik** [comment]
Glad you got it working.
