### ISSUE TITLE
Error at  line 198 

### ISSUE THREAD

**Issue by KatzeMau** [Yannik/qnap-letsencrypt#98]
**Platform/Firmware Information**
Model = TS-X53D
Internal Model = TS-X53B
Version = 4.5.1
Build Number = 20210107
Rsync Model = QNAP
Build Date = 2021-01-07

**Is this the latest firmware for your device?**
Yes 

**Issue Summary (provide relevant error messages and log output):**

[/share/Internal/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Mon, 25 Jan 2021 12:04:50 +0100
Renewing certificate...
qnap-letsencrypt version: 79e6e4e
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 20753
Parsing account key...
Parsing CSR...
Found domains: TheCatCloud.de
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying thecatcloud.de...
::ffff:46.223.83.191 - - [25/Jan/2021 12:05:10] "GET /.well-known/acme-challenge/zHKsipy8C0RDHD_IfGukzWYI39Uf_3lWHxV-RaDT50Y HTTP/1.1" 200 -
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for thecatcloud.de: {'expires': '2021-02-01T11:05:08Z', 'identifier': {'value': 'thecatcloud.de', 'type': 'dns'}, 'status': 'invalid', 'challenges': [{'status': 'invalid', 'type': 'http-01', 'token': 'zHKsipy8C0RDHD_IfGukzWYI39Uf_3lWHxV-RaDT50Y', 'error': {'detail': 'Fetching http://thecatcloud.de/.well-known/acme-challenge/zHKsipy8C0RDHD_IfGukzWYI39Uf_3lWHxV-RaDT50Y: Timeout during connect (likely firewall problem)', 'status': 400, 'type': 'urn:ietf:params:acme:error:connection'}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/10343607134/oLrzBg', 'validationRecord': [{'port': '80', 'addressesResolved': ['46.223.83.191'], 'url': 'http://thecatcloud.de/.well-known/acme-challenge/zHKsipy8C0RDHD_IfGukzWYI39Uf_3lWHxV-RaDT50Y', 'addressUsed': '46.223.83.191', 'hostname': 'thecatcloud.de'}]}]}
An error occured. Restoring system state.
./renew_certificate.sh: line 11: 20753 Killed                  "$PYTHON" ../HTTPServer.py  (wd: /share/CACHEDEV1_DATA/Internal/qnap-letsencrypt/tmp-webroot)
Start apache proxy: OK
Recover apache confiugre
Starting Qthttpd services: OK
[/share/Internal/qnap-letsencrypt] #

**Comment by aetasoul** [comment]
Hi @KatzeMau are you sure your NAS is reachable on port 80 from the internet?

**Comment by KatzeMau** [comment]
> Hi @KatzeMau Check your firewall settings. Port 80 is required by the acme challenge protocol.
> 
> Read [here](https://github.com/Yannik/qnap-letsencrypt#nas-setup.)
> 
> > Make sure your NAS is reachable from the public internet under the domain you want to get a certificate for on port 80.

Yes, port 80 is open.
Do i have to change a port in the qnap nas ?

**Comment by KatzeMau** [comment]
Okay im fucked up xD 
I cant access the nas anymore please help :/

**Comment by aetasoul** [comment]
1. Assign static IP address to your NAS in your network

2. On your NAS go to Control Panel, general settings, system administration and set as follow:
![image](https://user-images.githubusercontent.com/15131692/105970070-3de2ec80-6089-11eb-81dd-4a6ab710a792.png)

3. On your router configure the port forwarding 8080, 80 and 443

The port 80 must be open on your router and forwareded to the NAS, but need to be empty, the renew_certificate script create a listener on the port, if you publish your NAS web page on that port the renew will fail.

**Comment by KatzeMau** [comment]
The ports are all open, but it does not work!
But now i have a bigger problem, i changed the system port from 8080 to 80 and cant reach the nas surface anymore

**Comment by aetasoul** [comment]
That is because you force the connection under HTTPS, try to access the NAS with your local ip.

Suppose you NAS IP is 192.168.1.5, so try to access it like this https://192.168.1.5 or 192.168.1.5:443

**Comment by KatzeMau** [comment]
It says connection refused "The Website is not available 
<img width="1153" alt="Bildschirmfoto 2021-01-27 um 16 56 22" src="https://user-images.githubusercontent.com/46974624/106017365-adc09980-60c0-11eb-85fe-419981650b68.png">

**Comment by aetasoul** [comment]
You need to SSH into you NAS and manually update the HTTP port from 80 to 8080

Connect to your NAS with SSH, login as admin with your admin password and run this to disable the option that force only the HTTPS connections `/sbin/setcfg SYSTEM "Force SSL" 0` after that you have to restart the httpd service like this `/etc/init.d/thttpd.sh restart`

**Comment by KatzeMau** [comment]
Thank you, i fixed the port now BUT the sadly SSL does not work :/

Here the log, im still getting errors in the python file
and down there is some new weird stuff

[~] # cd /share/Internal
[/share/Internal] # ls
qnap-letsencrypt/  @Recently-Snapshot/	@Recycle/
[/share/Internal] # cd qnap-letsencrypt/
[/share/Internal/qnap-letsencrypt] # ls
1	    HTTPServer.py  openssl.cnf		  renew_certificate.sh*
acme-tiny/  init.sh*	   README.md		  tmp-webroot/
cacert.pem  letsencrypt/   renew_certificate.log
[/share/Internal/qnap-letsencrypt] # ./renew_certificate.sh
Checking whether to renew certificate on Wed, 27 Jan 2021 22:01:33 +0100
Renewing certificate...
qnap-letsencrypt version: 79e6e4e
Using python path: /share/CACHEDEV1_DATA/.qpkg/Python3/python3/bin/python3
Stopping Qthttpd hogging port 80..
Shutting down Qthttpd services: OK.
Started python HTTP server with pid 17482
Traceback (most recent call last):
  File "../HTTPServer.py", line 28, in <module>
    main()
  File "../HTTPServer.py", line 10, in main
    serve()
  File "../HTTPServer.py", line 20, in serve
    server = HTTPServerV6(('::', 80), SimpleHTTPRequestHandler)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Parsing account key...
Parsing CSR...
Found domains: TheCatCloud.de
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying thecatcloud.de...
Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 141, in get_crt
    assert (disable_check or _do_request(wellknown_url)[0] == keyauthorization)
  File "acme-tiny/acme_tiny.py", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error:
Url: http://thecatcloud.de/.well-known/acme-challenge/EQ3orwe9jX0JmqkXC3i0qMydqBIKu5ZrojXRgnUgZMw
Data: None
Response Code: 404
Response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />
<link rel="icon" href="/images/favicon.gif" type="image/gif" />
<style type="text/css">
body{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
background: #FFFFFF url('/cgi-bin/images/error/err_bg.jpg');
overflow: hidden;
color: #A4A3A3;
text-align: center;
}
.qnap_hyperlink a,.qnap_hyperlink a:link,.qnap_hyperlink a:visited{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
color: #A4A3A3;
}
.qnap_bar1{
width: 980px;
border-bottom: 1px solid #BCBCBC;
padding-top: 10px;
text-align: left;
margin: 0 auto;
}
.qnap_bar_img{padding-bottom: 10px;}
.main_div{
margin: 0 auto;
width: 700px;
padding-top: 100px;
}
.qnap_main_table{
width: 640px;
text-align: left;
position: relative;
left: 20px;
}
.qnap_ds1{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 26px;
font-weight: bold;
color: #CD0232;
padding-bottom: 20px;
position: relative;
top: -10px;
}
.qnap_ds2{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 15px;
color: #636161;
position: relative;
}
.qnap_c0{
text-align: center;
padding:190px 0px 25px 0px;
}
.qnap_c1{
width: 980px;
border-top: 1px solid #BCBCBC;
padding-top: 10px;
text-align: right;
margin: 0 auto;
}
</style>
<title>QNAP</title>
<script>
// Get cookie value function
function getCookie(name)
{
if (document.cookie.length>0)
{
var cStart = document.cookie.indexOf(name + "=");
var cEnd = 0;
if (cStart != -1)
{
cStart=cStart + name.length+1;
cEnd = document.cookie.indexOf(";",cStart);
if (cEnd==-1)
cEnd = document.cookie.length;
return unescape(document.cookie.substring(cStart,cEnd));
}
}
return '';
}
var DS = {};
DS.nasInfo = {
ver: 4.0
}
DS.nasInfo.lang = getCookie('nas_lang');
if((DS.nasInfo.lang == '') || (DS.nasInfo.lang==null)){
DS.nasInfo.lang = 'ENG';
}
DS.languageRead = function(lang){
var strObj = {str1:'',str2:'',str3:''}
switch(lang){
case 'ENG':
strObj.str1 = 'Error';
strObj.str2 = 'Page not found or the web server is currently unavailable. ';
strObj.str3 = 'Please contact the website administrator for help. ';
break;
case 'SCH':
strObj.str1 = '错误';
strObj.str2 = '网页不存在或目前无法联机至网页服务器。';
strObj.str3 = '请联络系统管理者寻求协助。';
break;
case 'TCH':
strObj.str1 = '錯誤';
strObj.str2 = '網頁不存在或目前無法連線至網頁伺服器。';
strObj.str3 = '請聯絡系統管理者尋求協助。';
break;
case 'CZE':
strObj.str1 = 'Chyba';
strObj.str2 = 'Stránka nebyla nalezena, nebo webový server není zrovna dostupný. ';
strObj.str3 = 'Pro asistenci kontaktujte prosím administrátora webu. ';
break;
case 'DAN':
strObj.str1 = 'Fejl';
strObj.str2 = 'Side ikke fundet eller webserveren er for øjeblikket utilgængelig. ';
strObj.str3 = 'Kontakt webstedets administrator for at få hjælp. ';
break;
case 'GER':
strObj.str1 = 'Fehler';
strObj.str2 = 'Seite nicht gefunden oder Webserver aktuell nicht verfügbar. ';
strObj.str3 = 'Bitte Webseitenadministrator kontaktieren. ';
break;
case 'SPA':
strObj.str1 = 'Error';
strObj.str2 = 'La página no existe o el servidor web no está disponible actualmente ';
strObj.str3 = 'Póngase en contacto con el administrador del sitio web para obtener ayuda. ';
break;
case 'FRE':
strObj.str1 = 'Erreur';
strObj.str2 = 'Page introuvable ou serveur Web indisponible. ';
strObj.str3 = 'Veuillez contacter l\'administrateur du site pour de l\'aide. ';
break;
case 'ITA':
strObj.str1 = 'Errore';
strObj.str2 = 'Pagina non trovata o server web attualmente non disponibile. ';
strObj.str3 = 'Rivolgersi all\'amministratore del sito web per assistenza. ';
break;
case 'JPN':
strObj.str1 = 'エラー';
strObj.str2 = 'ページが現在見つからない、またはWebサーバーが現在利用できません。 ';
strObj.str3 = 'ウェブサイト管理者に連絡して、相談してください。 ';
break;
case 'KOR':
strObj.str1 = '오류';
strObj.str2 = '페이지를 찾을 수 없거나 현재 웹 서버를 사용할 수 없습니다. ';
strObj.str3 = '웹사이트 관리자에게 연락하여 도움을 받으십시오. ';
break;
case 'NOR':
strObj.str1 = 'Feil';
strObj.str2 = 'Side ikke funnet eller webserveren er utilgjengelig for tiden. ';
strObj.str3 = 'Ta kontakt med administratoren for webområdet og få hjelp. ';
break;
case 'POL':
strObj.str1 = 'Błąd';
strObj.str2 = 'Strona nieodnaleziona lub serwer jest obecnie niedostępny. ';
strObj.str3 = 'Skontaktuj się z administratorem witryny, aby uzyskać pomoc. ';
break;
case 'RUS':
strObj.str1 = 'Ошибка';
strObj.str2 = 'Страница не найдена или веб сервер не доступен в настоящий момент.';
strObj.str3 = 'Пожалуйста, свяжитесь с администратором веб сайта для помощи.';
break;
case 'FIN':
strObj.str1 = 'Virhe';
strObj.str2 = 'Sivua ei löytynyt tai verkkopalvelin ei nyt ole käytettävissä. ';
strObj.str3 = 'Ota yhteys verkkosivuston ylläpitäjään ohjetta varten. ';
break;
case 'SWE':
strObj.str1 = 'Fel';
strObj.str2 = 'Sidan hittades inte eller så är webbservern för tillfället inte tillgänglig.';
strObj.str3 = 'Kontakta webbplatsens administratör för hjälp.';
break;
case 'DUT':
strObj.str1 = 'Fout';
strObj.str2 = 'Pagina niet gevonden, of de webserver is nu niet beschikbaar. ';
strObj.str3 = 'Neem contact op met de webbeheerder voor hulp. ';
break;
case 'ESM':
strObj.str1 = 'Error';
strObj.str2 = 'Página no encontrada o servidor Web no disponible actualmente. ';
strObj.str3 = 'Póngase en contacto con el administrador del sitio Web para obtener ayuda. ';
break;
case 'TUR':
strObj.str1 = 'Hata';
strObj.str2 = 'Sayfa bulunamadı veya web sunucusu şu an kullanılamıyor. ';
strObj.str3 = 'Lütfen yardım için web sitesi yöneticisiyle iletişime geçin. ';
break;
case 'THA':
strObj.str1 = 'ข้อผิดพลาด';
strObj.str2 = 'ไม่พบหน้าหรือเว็บเซิร์ฟเวอร์ไม่สามารถใช้งานได้ ';
strObj.str3 = 'โปรดติดต่อผู้ดูแลเว็บไซต์เพื่อขอความช่วยเหลือ ';
break;
case 'HUN':
strObj.str1 = 'Hiba';
strObj.str2 = 'Az oldal nem található vagy a webkiszolgáló jelenleg nem elérhető. ';
strObj.str3 = 'Kérjük, értesítse a weboldalt rendszergazdáját és kérjen tőle segítséget. ';
break;
case 'POR':
strObj.str1 = 'Erro';
strObj.str2 = 'Página não encontrada ou o servidor Web actualmente não está disponível. ';
strObj.str3 = 'Contacte o administrador do site Web para obter ajuda. ';
break;
case 'GRK':
strObj.str1 = 'Σφάλμα';
strObj.str2 = 'Η σελίδα δεν βρέθηκε ή ο διακομιστής ιστού είναι μη διαθέσιμος αυτή τη στιγμή. ';
strObj.str3 = 'Επικοινωνήστε με τον διαχειριστή του ιστοτόπου για βοήθεια. ';
break;
case 'ROM':
strObj.str1 = 'Eroare';
strObj.str2 = 'Pagina nu a fost găsită sau serverul web este indisponibil momentan. ';
strObj.str3 = 'Contactaţi administratorul site-ului web pentru a obţine asistenţă.';
break;
default:
strObj.str1 = 'Error';
strObj.str2 = 'Page not found or the web server is currently unavailable. ';
strObj.str3 = 'Please contact the website administrator for help. ';
break;
}
return strObj;
}
DS.strObj = DS.languageRead(DS.nasInfo.lang);
</script>
</head>
<body>

<div id="index_main_div">

<div style="height:12px;width:980px;"></div>


<div class="qnap_bar1">
<div class="qnap_bar_img"><img src="/cgi-bin/images/error/logo_gray.png"></div>
</div>
<div class="main_div">
<div class="qnap_main_table">
<table border="0" cellpadding="0">
<tr>
<td style="padding-right:80px;"><img src="/cgi-bin/images/error/forbidden.png"></td>
<td>
<div class="qnap_ds1">
<script>document.write(DS.strObj.str1)</script>
</div>
<div class="qnap_ds2">
<script>document.write(DS.strObj.str2 + DS.strObj.str3)</script>
</div>
</td>
</tr>
</table>
</div>
</div>
<div class="qnap_c0 qnap_hyperlink">
<div class="qnap_c1">Copyright &copy;2021 <a href="http://www.qnap.com" target="_blank">QNAP Systems, Inc.</a> All Rights Reserved.
</div>
</div>
</div>
</body>
</html>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acme-tiny/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme-tiny/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "acme-tiny/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to tmp-webroot/.well-known/acme-challenge/EQ3orwe9jX0JmqkXC3i0qMydqBIKu5ZrojXRgnUgZMw, but couldn't download http://thecatcloud.de/.well-known/acme-challenge/EQ3orwe9jX0JmqkXC3i0qMydqBIKu5ZrojXRgnUgZMw: Error:
Url: http://thecatcloud.de/.well-known/acme-challenge/EQ3orwe9jX0JmqkXC3i0qMydqBIKu5ZrojXRgnUgZMw
Data: None
Response Code: 404
Response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="-1" />
<link rel="shortcut icon" href="/images/favicon.gif" type="image/gif" />
<link rel="icon" href="/images/favicon.gif" type="image/gif" />
<style type="text/css">
body{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
background: #FFFFFF url('/cgi-bin/images/error/err_bg.jpg');
overflow: hidden;
color: #A4A3A3;
text-align: center;
}
.qnap_hyperlink a,.qnap_hyperlink a:link,.qnap_hyperlink a:visited{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 11px;
color: #A4A3A3;
}
.qnap_bar1{
width: 980px;
border-bottom: 1px solid #BCBCBC;
padding-top: 10px;
text-align: left;
margin: 0 auto;
}
.qnap_bar_img{padding-bottom: 10px;}
.main_div{
margin: 0 auto;
width: 700px;
padding-top: 100px;
}
.qnap_main_table{
width: 640px;
text-align: left;
position: relative;
left: 20px;
}
.qnap_ds1{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 26px;
font-weight: bold;
color: #CD0232;
padding-bottom: 20px;
position: relative;
top: -10px;
}
.qnap_ds2{
font-family:Verdana, Lucida Grande, Tahoma, Arial, Helvetica, sans-serif;
font-size: 15px;
color: #636161;
position: relative;
}
.qnap_c0{
text-align: center;
padding:190px 0px 25px 0px;
}
.qnap_c1{
width: 980px;
border-top: 1px solid #BCBCBC;
padding-top: 10px;
text-align: right;
margin: 0 auto;
}
</style>
<title>QNAP</title>
<script>
// Get cookie value function
function getCookie(name)
{
if (document.cookie.length>0)
{
var cStart = document.cookie.indexOf(name + "=");
var cEnd = 0;
if (cStart != -1)
{
cStart=cStart + name.length+1;
cEnd = document.cookie.indexOf(";",cStart);
if (cEnd==-1)
cEnd = document.cookie.length;
return unescape(document.cookie.substring(cStart,cEnd));
}
}
return '';
}
var DS = {};
DS.nasInfo = {
ver: 4.0
}
DS.nasInfo.lang = getCookie('nas_lang');
if((DS.nasInfo.lang == '') || (DS.nasInfo.lang==null)){
DS.nasInfo.lang = 'ENG';
}
DS.languageRead = function(lang){
var strObj = {str1:'',str2:'',str3:''}
switch(lang){
case 'ENG':
strObj.str1 = 'Error';
strObj.str2 = 'Page not found or the web server is currently unavailable. ';
strObj.str3 = 'Please contact the website administrator for help. ';
break;
case 'SCH':
strObj.str1 = '错误';
strObj.str2 = '网页不存在或目前无法联机至网页服务器。';
strObj.str3 = '请联络系统管理者寻求协助。';
break;
case 'TCH':
strObj.str1 = '錯誤';
strObj.str2 = '網頁不存在或目前無法連線至網頁伺服器。';
strObj.str3 = '請聯絡系統管理者尋求協助。';
break;
case 'CZE':
strObj.str1 = 'Chyba';
strObj.str2 = 'Stránka nebyla nalezena, nebo webový server není zrovna dostupný. ';
strObj.str3 = 'Pro asistenci kontaktujte prosím administrátora webu. ';
break;
case 'DAN':
strObj.str1 = 'Fejl';
strObj.str2 = 'Side ikke fundet eller webserveren er for øjeblikket utilgængelig. ';
strObj.str3 = 'Kontakt webstedets administrator for at få hjælp. ';
break;
case 'GER':
strObj.str1 = 'Fehler';
strObj.str2 = 'Seite nicht gefunden oder Webserver aktuell nicht verfügbar. ';
strObj.str3 = 'Bitte Webseitenadministrator kontaktieren. ';
break;
case 'SPA':
strObj.str1 = 'Error';
strObj.str2 = 'La página no existe o el servidor web no está disponible actualmente ';
strObj.str3 = 'Póngase en contacto con el administrador del sitio web para obtener ayuda. ';
break;
case 'FRE':
strObj.str1 = 'Erreur';
strObj.str2 = 'Page introuvable ou serveur Web indisponible. ';
strObj.str3 = 'Veuillez contacter l\'administrateur du site pour de l\'aide. ';
break;
case 'ITA':
strObj.str1 = 'Errore';
strObj.str2 = 'Pagina non trovata o server web attualmente non disponibile. ';
strObj.str3 = 'Rivolgersi all\'amministratore del sito web per assistenza. ';
break;
case 'JPN':
strObj.str1 = 'エラー';
strObj.str2 = 'ページが現在見つからない、またはWebサーバーが現在利用できません。 ';
strObj.str3 = 'ウェブサイト管理者に連絡して、相談してください。 ';
break;
case 'KOR':
strObj.str1 = '오류';
strObj.str2 = '페이지를 찾을 수 없거나 현재 웹 서버를 사용할 수 없습니다. ';
strObj.str3 = '웹사이트 관리자에게 연락하여 도움을 받으십시오. ';
break;
case 'NOR':
strObj.str1 = 'Feil';
strObj.str2 = 'Side ikke funnet eller webserveren er utilgjengelig for tiden. ';
strObj.str3 = 'Ta kontakt med administratoren for webområdet og få hjelp. ';
break;
case 'POL':
strObj.str1 = 'Błąd';
strObj.str2 = 'Strona nieodnaleziona lub serwer jest obecnie niedostępny. ';
strObj.str3 = 'Skontaktuj się z administratorem witryny, aby uzyskać pomoc. ';
break;
case 'RUS':
strObj.str1 = 'Ошибка';
strObj.str2 = 'Страница не найдена или веб сервер не доступен в настоящий момент.';
strObj.str3 = 'Пожалуйста, свяжитесь с администратором веб сайта для помощи.';
break;
case 'FIN':
strObj.str1 = 'Virhe';
strObj.str2 = 'Sivua ei löytynyt tai verkkopalvelin ei nyt ole käytettävissä. ';
strObj.str3 = 'Ota yhteys verkkosivuston ylläpitäjään ohjetta varten. ';
break;
case 'SWE':
strObj.str1 = 'Fel';
strObj.str2 = 'Sidan hittades inte eller så är webbservern för tillfället inte tillgänglig.';
strObj.str3 = 'Kontakta webbplatsens administratör för hjälp.';
break;
case 'DUT':
strObj.str1 = 'Fout';
strObj.str2 = 'Pagina niet gevonden, of de webserver is nu niet beschikbaar. ';
strObj.str3 = 'Neem contact op met de webbeheerder voor hulp. ';
break;
case 'ESM':
strObj.str1 = 'Error';
strObj.str2 = 'Página no encontrada o servidor Web no disponible actualmente. ';
strObj.str3 = 'Póngase en contacto con el administrador del sitio Web para obtener ayuda. ';
break;
case 'TUR':
strObj.str1 = 'Hata';
strObj.str2 = 'Sayfa bulunamadı veya web sunucusu şu an kullanılamıyor. ';
strObj.str3 = 'Lütfen yardım için web sitesi yöneticisiyle iletişime geçin. ';
break;
case 'THA':
strObj.str1 = 'ข้อผิดพลาด';
strObj.str2 = 'ไม่พบหน้าหรือเว็บเซิร์ฟเวอร์ไม่สามารถใช้งานได้ ';
strObj.str3 = 'โปรดติดต่อผู้ดูแลเว็บไซต์เพื่อขอความช่วยเหลือ ';
break;
case 'HUN':
strObj.str1 = 'Hiba';
strObj.str2 = 'Az oldal nem található vagy a webkiszolgáló jelenleg nem elérhető. ';
strObj.str3 = 'Kérjük, értesítse a weboldalt rendszergazdáját és kérjen tőle segítséget. ';
break;
case 'POR':
strObj.str1 = 'Erro';
strObj.str2 = 'Página não encontrada ou o servidor Web actualmente não está disponível. ';
strObj.str3 = 'Contacte o administrador do site Web para obter ajuda. ';
break;
case 'GRK':
strObj.str1 = 'Σφάλμα';
strObj.str2 = 'Η σελίδα δεν βρέθηκε ή ο διακομιστής ιστού είναι μη διαθέσιμος αυτή τη στιγμή. ';
strObj.str3 = 'Επικοινωνήστε με τον διαχειριστή του ιστοτόπου για βοήθεια. ';
break;
case 'ROM':
strObj.str1 = 'Eroare';
strObj.str2 = 'Pagina nu a fost găsită sau serverul web este indisponibil momentan. ';
strObj.str3 = 'Contactaţi administratorul site-ului web pentru a obţine asistenţă.';
break;
default:
strObj.str1 = 'Error';
strObj.str2 = 'Page not found or the web server is currently unavailable. ';
strObj.str3 = 'Please contact the website administrator for help. ';
break;
}
return strObj;
}
DS.strObj = DS.languageRead(DS.nasInfo.lang);
</script>
</head>
<body>

<div id="index_main_div">

<div style="height:12px;width:980px;"></div>


<div class="qnap_bar1">
<div class="qnap_bar_img"><img src="/cgi-bin/images/error/logo_gray.png"></div>
</div>
<div class="main_div">
<div class="qnap_main_table">
<table border="0" cellpadding="0">
<tr>
<td style="padding-right:80px;"><img src="/cgi-bin/images/error/forbidden.png"></td>
<td>
<div class="qnap_ds1">
<script>document.write(DS.strObj.str1)</script>
</div>
<div class="qnap_ds2">
<script>document.write(DS.strObj.str2 + DS.strObj.str3)</script>
</div>
</td>
</tr>
</table>
</div>
</div>

***
--



<div class="qnap_c0 qnap_hyperlink">
<div class="qnap_c1">Copyright &copy;2021 <a href="http://www.qnap.com" target="_blank">QNAP Systems, Inc.</a> All Rights Reserved.
</div>
</div>
</div>
</body>
</html>

An error occured. Restoring system state.
./renew_certificate.sh: line 12: kill: (17482) - No such process
[/share/Internal/qnap-letsencrypt] #

**Comment by KatzeMau** [comment]
**ITS FIXED** 
You must shutdown QuFirewall, it blocks letsencrypt (I block every ip that is not from germany or spain)
Thanks @aetasoul For you're great help !

**Comment by Yannik** [comment]
Good job on solving that, @KatzeMau. And thank you @aetasoul for your support.
