### ISSUE TITLE
How to reinstall?

### ISSUE THREAD

**Issue by aski71** [Yannik/qnap-letsencrypt#99]
Hi,

I've been using qnap-letsencrypt for years and left it untouched.
Now I'm experiencing troubles cause by this:
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

So I tried to reinstall the latest qnap-letsencrypt but already fail at the first step:

[/share/MD0_DATA/letsencrypt] # git config --system http.sslVerify true
error: could not lock config file /Apps/git/etc/gitconfig: No such file or directory

Can you help?

Thanks, Alex

**Comment by Yannik** [comment]
Hi Alex,
can you please fill out the template that you get when opening a new issue.

**Comment by aetasoul** [comment]
Hi Alex,
Can you share the output of this command `sudo git -c core.editor=ls\ -al config --system --edit`, it will show where the gitconfig file is located.

It must be something similar to this `/share/CACHEDEV1_DATA/.qpkg/Entware/etc/gitconfig`

Can you share also the git version and tell me if you have installed git with Entware or using the QNAP App-Center.

**Comment by aetasoul** [comment]
Hi aski71,
Which is your git version? It seems to require an update

**Comment by aski71** [comment]
Sorry, I forgot to mention: 2.1.0

**Comment by aetasoul** [comment]
Try to update, if there is some, else try with `git config --global --add http.sslVersion tlsv1.2`

**Comment by aski71** [comment]
Unfortunately no update for git on my TS-459 is available.
Tried the above. Same result:

[/share/MD0_DATA/letsencrypt] # git config --global --add http.sslVersion tlsv1.2
[/share/MD0_DATA/letsencrypt] # git clone https://github.com/Yannik/qnap-letsencrypt.git
Cloning into 'qnap-letsencrypt'...
fatal: unable to access 'https://github.com/Yannik/qnap-letsencrypt.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by aetasoul** [comment]
Try to remove ssl check `git config --system http.sslVerify false` and clone again, if this doesn't work read below.

The tlsv1 protocol was deprecated (server side) from github in 2018, so there are two solutions:
*  Upgrade you git version
* Clone the repo with ssh and not over https

The version [2.1.0](https://github.com/git/git/releases/tag/v2.1.0) was released in 2014, very old version.

To upgrade your git version I suggest to uninstal from the app center, and follow the @Yannik  tips on how to install with entware as described [here](https://github.com/Yannik/qnap-letsencrypt#installing-git).

The second option, more complex, allows you to clone the repo without ssl. You can clone the repo with `git clone git@github.com:Yannik/qnap-letsencrypt.git`, but first you need to [add a new public key](https://github.com/settings/ssh/new) to your github account.

**Comment by aski71** [comment]
Ok, I decided to remove 2.1.0, install entware as described in the link. 
Had to additionally install python 2.5 and git-http afterwards.
Now everything's up and running again.

Thank you all for your help and patience!

**Comment by aetasoul** [comment]
No problem 👍
